---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oauth2-proxy-valkey
  namespace: oauth2-proxy
spec:
  serviceName: oauth2-proxy-valkey
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy-valkey
  template:
    metadata:
      labels:
        app: oauth2-proxy-valkey
    spec:
      containers:
        - name: oauth2-proxy-valkey
          image: valkey/valkey:8.1.4-alpine
          env:
            - name: TZ
              value: Europe/Zurich
          ports:
            - containerPort: 6379
          startupProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
      restartPolicy: Always
      automountServiceAccountToken: false
