---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-garage
  namespace: gitlab
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./script/helm
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 5m
  values:
    garage:
      replicationFactor: "1"
    persistence:
      data:
        size: 5Gi
      meta:
        size: 250Mi
