---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${BASE_DOMAIN/./-}-sso
  namespace: usenet
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sonarr-internal
      sectionName: sonarr
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sonarr-external
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: radarr-internal
      sectionName: radarr
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: radarr-external
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sabnzbd-internal
      sectionName: sabnzbd
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sabnzbd-external
  oidc:
    provider:
      issuer: https://sso.${BASE_DOMAIN}/realms/master
    clientID: envoy-gateway
    clientSecret:
      name: ${BASE_DOMAIN/./-}-sso-client-secret
