---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: ingress-nginx
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
  namespace: ingress-nginx
subsets:
  - addresses:
      - ip: 10.0.1.104
    ports:
      - port: 443
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    cloudflare-operator.io/content: ${BASE_DOMAIN}
    cloudflare-operator.io/type: CNAME
spec:
  rules:
    - host: home.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 443
