---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-valkey
  namespace: gitlab
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: gitlab-valkey
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  type: ClusterIP
