---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 5m
  values:
    crds:
      create: false
  install:
    crds: Skip
  upgrade:
    crds: Skip
