apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Mfr8u2SSm8VSoVdU9Gyw+0HFHDDTBSyR3zPSnQ1uoZlY1RUcu25KF2Z0fXdhmfnGw9+C733i8GQYuFhT7qif65dH76vE/mGLHZQoXFJBC3pS39Xqqpixp69WqgK+2s6ZG9eqnUa6c/QWrg9s9mYO7NPMDzW8FbAHjJHGToUuLd401Kra7mgmt3nj89rpikXOTnBAdPRSBok8lbW9ZV7X2T5GuFzDObFBC3+NpyUIDutykq5Z4s1Ahvvs8nkmSto8PYKM+NjorHT54AH36KuthUL0RNJBEd90ICAiAFEQTvPZclpqwTCSQrLmIqGzzx7XssnqP8KO9RDU8xtTfN+AFBo78/kEqkgnAkoormne0l6qZCZYYeG8WPEYZrWNbkWaBZwuwsTj6V4tovIhiGLp7jGGePrDD6skiXEeBRs2zc+sLJ+mriRXONzh9lXtC0LoPUFKiS5byMBrpImtZHSLNqhh+2jY13XVB6Bzv05YN8qrvvSzFeLYbVnLW9BAyQrDmX1jjAINfFpLqHp99KxjuOV5bLTkoPJF+cdLafkpMBWeiXI4NETdoy6DdSRVuYxIlRHyZdv6ShXgYs4TG5eJd5Nv/zxYLJdpCK+XsVwaXQsA6l8NZEyvC32/ZvSxrKTRJ+Jav5ZFa3bGRT6po18aT4A/N/aozBj3Fo1WcCrdtTo9OQJo2lqQHPApfMxCAcHeN82woomyB9RxWGE9okcQC0rKbwq4o9SUYyVKtZTkuSGQMvxG8LS1fvS0tm9CEkD5ospNaJroYkjliRcp1LGUDydvEtxML1iihhlDJOMr1h5RqOsHAq7fhR40P7fXmdIhpYG4OYiH1tomU+aY+sclxporDQg1YKpAHv6tRV8f+5eYiqm4/aX1gex+NkrOqbUfJ0XAUIvMH4LlaihTZ0ZfMzy35GWi7f7V6BcLZ1RQLII2nByZzmRMBdorvOIC0F3S8LSJZ08+etY10FyXMGTCzXrkCjfpqZCCkLnVusv2SC/p0vkjSB8zsp/mrDsjTHJjS5Kyh+Frr4w9/Pu6zQCj8dYNNLN8V2eDSDAxP9k5+gLqn31MDVcsUcnLGen25QQ6D/j2eeiMbrDssNZAgeVzdr+/UNunqSM+lkkVGELoYvfG,iv:VjVWytP+Wh6yZIazoIB2vpqk8vv8BgcKjHwp00nEDC8=,tag:9O4rTJDX23+0CcXdrXzEaA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T17:08:19Z"
    mac: ENC[AES256_GCM,data:3oTZEzcmZHhuYeb87qSxt7aNumzm5ij8sId/XN/x6X9FXMdpQl0sNB9gowDZLFXD/ffSx8I5vtp9twHVnhKKzrOCCVBlEW41kt3hLg6OrKe0Jwt1KA+dKv44zwsQ3ypFSM2EAgd/MypvoEF0KVLADL3kkxHAvywxK2QqLeCnCgU=,iv:LHqz1xSNBwfXvPQtCsZWCtiBi0Bgdw2XpbqJ9oooBBg=,tag:kfftD9HxWb75zR7IooK2sA==,type:str]
    pgp:
        - created_at: "2026-02-24T21:09:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//Q/MV45penMh2QpvJV/ylwQ9MOYVXgVpQeii2Y/akISbj
            ytYLf1L91zR+d7aeqDXWp2AsGFqc1CAABGoidZ5FkjmsIOkhdT2jDkxdYTVX8taa
            5kM4anvcLhxsZhqlSdPR67/jmeiPHA7WbfullwgaW07zsdohrVdbzfPETNmzqlde
            kHJ5p40am+tU6DbvK6Y0Fyb9lEOXc/2TaoP/t/yHimwa0jXYCh/wJ08FOUzCWKti
            cLlCAxPe/zdi5M7gYOTPY2NbhVN+ccfkJGbck7T76V46OlFtIX2hY7cGJ5FJSlt1
            z9kxc9QIk7+DCsD5nFO5jsq/x3Tptr5zl8TBl69lXoIEaLOnRiCjt71nPnum0W7d
            qA2v/g+pRQE6Co1GQqSrvm6gEygnYe5kU1q49Od9UF4dGRL4xCpt6ZcEMJS7PGhN
            TAdE9e9Rn6yRLDZJFpGY9H6HV69uc6OJcTP1xAK0QCIPWSyJAKf+McDaYtBxL+Qz
            QMKRK2K+ucOriuuWPrGQfPHeRmnslUQMKrSXotbI89klKizR3RdbHRBEXhcmQxy3
            2Hs9emmfyNUb5++LSzOmFE9muqWRyaGwI3f1pUdiypBzOGYAwMiNVfv3GRijwGKi
            emu5TxxDmNGGhfrMC5i/bTwYIDB4Or7HDz8tb4Je4T9b2b8Q3wsmDy53vsNUbGvU
            aAEJAhCgt0DR9VHdI1uXuwB35V+/BAvJ9GBIK1g7HCmJbguDdDuNlSHOmOKQ/IOD
            l89ntpLlV9WUW0xsZnYv0UDATFnkCWQJrAYQQ5ZjQ+pmhi4rTOw8Jm/ahGu0VCqr
            WSXoGKQUOKO1
            =+a3K
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.12.1
