apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:HGSEhSwmn92rvcUr0DZOvqLHjTvk48PFI2znhBaQ4nxmfNNE+TeLhUAJL/4O8nSI3seXy6uFJn6Etgic+uAgVO069k0EhPOKGJc2Dx53Oj6ziExEjFsd4rmtj/ITzk9r4irn8B1qW1olWJ+nwlBv7h/HANFPoSx1vKY93is0aZeXSeJf2cXZ8zr9tpN6fgBZRv/jjI9/j1sx0VcjK1vM2q0dlaNYn2MIjp/EAyfLJlc/uINIQvQLZEwlJfNAaIWMSjt28qrBwNVcCTsl8K5f77PCSpNQcCpLbRp5l6r6sFn6eY8fNYkx7elzK//RtxllRm1B8/IdXDOD5Mu3X2SCPuJ/CxUuziIWddOok6vWHpsMtog5rPUSzQGlu+GCYi+WZv6VaZlZTETqlRLxYXVs6YEyOGeb0NiXnZAVOZ2INibaD9Xr9DMj1a1anRVHVyWq/BCfjwafNRXBYxFueM62dP6YSRJG1Je1+scvisL5fzW7nw8wgAUeSb9bJHuK+fkJKAHTYqJRJz7HRTcabNFVnZVM3EyVPgaXwYlL4rMbiaxkKleT26RNpnGvw8aIUiMmbeuUPc/Gmyq0ELlANG9O8jmcjd9pquswMntwvn5ymyrdFaduuLfl7o8bsa9j39qJLJHjT87l3ODiLC0aJXdohoDYhYQ9CBLrVVrdkZEC4Fvw8v6m7lmyJKuxtMgc+Wvu1GE0MgZtdChl9WgxURZxopfi788pLOjwreLEIzK1/Bs=,iv:+XqYR7H7mTcDjrhsrwM8dmTdOxMbAOH34ruIoy4o1Zc=,tag:dxcsW9nW+DOSDssXooHH9Q==,type:str]
sops:
    lastmodified: "2025-11-21T12:43:12Z"
    mac: ENC[AES256_GCM,data:tuqTObxFkFY/aIeUyefJEO0qxklwJ3WA+yJhIK2CaArD3NDgwSvDM5xEqDu3CCRBs6+k3i8Y4Bbr8V+NWWCPepIJZHl5u58B9Pig+REE/OFZF1kAy5vdNSCMW3eKa/3gnqMD8X5nKT4EAFkmJ2MIxaj/sd24bqb3OIhd+JBTiNI=,iv:Wub35km4UwyKCWUfsnsAKNj2jaggf9QelMOtbPhqUZ4=,tag:hRjOgW1qHkfAbwQxu6jrvg==,type:str]
    pgp:
        - created_at: "2025-11-21T12:43:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ/6AiuSfKxoUGy/QIF1SWhw1k7ZdXtB5PcqLjseHjZMnnzv
            Qe5Jotelf7dwVXuagS7TztVnscIBX258xPw91zUnDZC6LrmPPzHhUy/67gADC78E
            Fix9Ysd9PcprNBr7A932ohmoYnYvzAMwQgF3ejcshBn59sflrzFaqwCv8ZPvCViV
            GscVp6tODtXF8rUr3orACUodyDbgT2L2VMLhJGaxzEMYwzd7iHZzd7bckaLs8T5z
            IA7smYBCHt2kW0l8DP3GFTqBwIt6IpECImehKyENUWVzh+kxkY6nWSO3OsVf9W1c
            E/IFrvBEa2s2odjoIg5KGWx400Jj/AudZ/p/1KJkcRRbNovzVtOK/vxNL5wWXRKS
            hesJ37bnnwa1wqVblJV7Pvp+Bk530EzHaWQqu69k42eL1YrnL35v5GM32D1hUcp/
            DWbV5ppKQhT5/P60415HqmbnG7/Br8OfMnql4rnTKGwPqYNEE6L7JzJVg8qV+Evy
            G+80Ct31kCm2cH8H385vK146OOP5z8eCABYnKzWOxkAJOHLeDHFMBwAMp+ajZFLk
            Dc62cRyasXyJcUxox2YUeVLKst2Txzw+Jw+imKaMwc6PaD2E354JCqY9eTl8Gyc7
            ZkXEqSgQA6EBIecL+wsuIk2zzXL1pj5bDIIVwRa7BL14EDusuONozP1JUouukgHU
            ZgEJAhAygv6mepcYz0WjWlQazbEkQbS0qM2pqKG0j0ounY6bhcGtqJYtVbADHp0j
            qV7gpkj955bFZJLz7AN9slQPEza6cpl2/nOtPqT7kVotp5Soz/Xvc2gE8YsrFkrr
            pcGbYYFpSQ==
            =QINs
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
