---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 5m
  values:
    crds:
      create: false
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
        namespace: monitoring
        annotations:
          kustomize.toolkit.fluxcd.io/substitute: disabled
  install:
    crds: Skip
  upgrade:
    crds: Skip
