---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: ${BASE_DOMAIN/./-}-v4
  namespace: cloudflare-operator
spec:
  name: ${BASE_DOMAIN}
  type: A
  ipRef:
    name: ${BASE_DOMAIN/./-}-v4
  proxied: true
  ttl: 1
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: ${BASE_DOMAIN/./-}-v6
  namespace: cloudflare-operator
spec:
  name: ${BASE_DOMAIN}
  type: AAAA
  ipRef:
    name: ${BASE_DOMAIN/./-}-v6
  proxied: true
  ttl: 1
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: vpn-${BASE_DOMAIN/./-}
  namespace: cloudflare-operator
spec:
  name: vpn.${BASE_DOMAIN}
  type: A
  ipRef:
    name: ${BASE_DOMAIN/./-}-v4
  proxied: false
  ttl: 60
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: docker-srv-${BASE_DOMAIN/./-}-v4
  namespace: cloudflare-operator
spec:
  name: docker.srv.${BASE_DOMAIN}
  type: A
  ipRef:
    name: docker-v4
  proxied: false
  ttl: 60
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: docker-srv-${BASE_DOMAIN/./-}-v6
  namespace: cloudflare-operator
spec:
  name: docker.srv.${BASE_DOMAIN}
  type: AAAA
  ipRef:
    name: docker-v6
  proxied: false
  ttl: 60
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: teslamate-${BASE_DOMAIN/./-}
  namespace: cloudflare-operator
spec:
  name: teslamate.${BASE_DOMAIN}
  type: CNAME
  content: docker.srv.${BASE_DOMAIN}
  proxied: true
  ttl: 1
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: teslamate-grafana-${BASE_DOMAIN/./-}
  namespace: cloudflare-operator
spec:
  name: teslamate-grafana.${BASE_DOMAIN}
  type: CNAME
  content: docker.srv.${BASE_DOMAIN}
  proxied: true
  ttl: 1
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: sso-${BASE_DOMAIN/./-}
  namespace: cloudflare-operator
spec:
  name: sso.${BASE_DOMAIN}
  type: CNAME
  content: docker.srv.${BASE_DOMAIN}
  proxied: true
  ttl: 1
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: checkmk-srv-${BASE_DOMAIN/./-}-v4
  namespace: cloudflare-operator
spec:
  name: checkmk.srv.${BASE_DOMAIN}
  type: A
  ipRef:
    name: checkmk-v4
  proxied: false
  ttl: 60
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: checkmk-srv-${BASE_DOMAIN/./-}-v6
  namespace: cloudflare-operator
spec:
  name: checkmk.srv.${BASE_DOMAIN}
  type: AAAA
  ipRef:
    name: checkmk-v6
  proxied: false
  ttl: 60
  interval: 5m
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: ${BASE_DOMAIN/./-}-mx
  namespace: cloudflare-operator
spec:
  content: ${MX_SERVER}
  name: ${BASE_DOMAIN}
  priority: 10
  proxied: false
  ttl: 1
  type: MX
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: ${BASE_DOMAIN/./-}-spf
  namespace: cloudflare-operator
spec:
  content: ${SPF_CONTENT}
  name: ${BASE_DOMAIN}
  proxied: false
  ttl: 1
  type: TXT
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: ${BASE_DOMAIN/./-}-dkim
  namespace: cloudflare-operator
spec:
  content: ${DKIM_CONTENT}
  name: sel2011a._domainkey.${BASE_DOMAIN}
  proxied: false
  ttl: 1
  type: TXT
---
apiVersion: cf.containeroo.ch/v1beta1
kind: DNSRecord
metadata:
  name: ${BASE_DOMAIN/./-}-srv
  namespace: cloudflare-operator
spec:
  name: ${BASE_DOMAIN}
  data:
    service: _autodiscover
    proto: _tcp
    port: "443"
    name: ${BASE_DOMAIN}
    priority: "0"
    weight: "100"
    target: ${SRV_TARGET}
  proxied: false
  ttl: 1
  type: SRV
