---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-operator
  namespace: cloudflare-operator
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cloudflare-operator
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: containeroo
        namespace: flux-system
      interval: 5m
  values:
    metrics:
      prometheusRule:
        enabled: true
        namespace: monitoring
      podMonitor:
        enabled: true
        namespace: monitoring
