---
apiVersion: cloudflare-operator.io/v1
kind: IP
metadata:
  name: ${BASE_DOMAIN/./-}-v4
spec:
  type: dynamic
  ipSources:
    - url: https://checkip.amazonaws.com
    - url: https://api.ipify.org
    - url: https://ipv4.hostpoint.ch
---
apiVersion: cloudflare-operator.io/v1
kind: IP
metadata:
  name: ${BASE_DOMAIN/./-}-v6
spec:
  type: static
  address: ${IPV6_PREFIX}::200
