---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvme
  namespace: storage-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: local-path-provisioner
      version: 0.0.34
      sourceRef:
        kind: HelmRepository
        name: containeroo
        namespace: flux-system
      interval: 5m
  values:
    configmap:
      name: nvme-local-path-provisioner
      teardown: |-
        #!/bin/sh

        archived_path="$(dirname $${VOL_DIR})/archived-$(basename $${VOL_DIR})"
        mv $${VOL_DIR} $${archived_path}
    nodePathMap:
      - node: k3s.srv.${BASE_DOMAIN}
        paths:
          - /mnt/disk04/data
    storageClass:
      defaultClass: true
      name: nvme
