---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: teslamate
  namespace: teslamate
spec:
  podSecurityContext:
    runAsUser: 0
  backend:
    s3:
      bucket: teslamate
  backup:
    schedule: "0 1,13 * * *"
  check:
    schedule: "0 3 * * *"
  prune:
    retention:
      keepDaily: 2
      keepLast: 14
    schedule: "0 2 * * *"
