---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 5m
  chart:
    spec:
      chart: paperless
      version: 9.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.12.0
    env:
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_TIME_ZONE: Europe/Zurich
      PAPERLESS_REDIS: redis://paperless-redis-master.paperless.svc.cluster.local:6379
      PAPERLESS_ALLOWED_HOSTS: paperless.local.${BASE_DOMAIN}
      PAPERLESS_CORS_ALLOWED_HOSTS: https://paperless.local.${BASE_DOMAIN}
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: "True"
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTH_REQUEST_EMAIL
      PAPERLESS_URL: https://paperless.local.${BASE_DOMAIN}
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.${BASE_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.${BASE_DOMAIN}/oauth2/start?rd=$scheme://$best_http_host$request_uri"
          nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
          nginx.ingress.kubernetes.io/whitelist-source-range: ${LAN_NETWORK_RANGE_V4},${LAN_NETWORK_RANGE_V6},${POD_NETWORK_RANGE_V4},${POD_NETWORK_RANGE_V6}
          cf.containeroo.ch/ignore: "true"
        hosts:
          - host: paperless.local.${BASE_DOMAIN}
            paths:
              - path: /
    persistence:
      data:
        enabled: true
        storageClass: nvme
        size: 1Gi
        annotations:
          k8up.io/backup: "true"
      media:
        enabled: true
        storageClass: nvme
        size: 1Gi
        annotations:
          k8up.io/backup: "true"
      consume:
        enabled: true
        size: 1Gi
        emptyDir:
          enabled: true
    redis:
      enabled: true
      auth:
        enabled: false
      architecture: standalone
  valuesFrom:
    - kind: Secret
      name: paperless-helm-values
      optional: false
