---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-postgres-16
  namespace: gitlab
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
  backup:
    barmanObjectStore:
      destinationPath: s3://db-backups
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup
          key: accessKey
        secretAccessKey:
          name: db-backup
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 30d
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-postgres
  namespace: gitlab
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
      import:
        type: microservice
        databases:
          - gitlabhq_production
        source:
          externalCluster: gitlab-postgres-16
  backup:
    barmanObjectStore:
      destinationPath: s3://db-backups
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup
          key: accessKey
        secretAccessKey:
          name: db-backup
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 30d
  monitoring:
    enablePodMonitor: true
  externalClusters:
    - name: gitlab-postgres-16
      connectionParameters:
        host: gitlab-postgres-16-r.gitlab.svc.cluster.local
        user: gitlab
        dbname: gitlabhq_production
      password:
        name: gitlab-postgres-16-app
        key: password
