---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: gitlab
  namespace: gitlab
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://db-backups
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: db-backup
        key: accessKey
      secretAccessKey:
        name: db-backup
        key: secretKey
    wal:
      compression: gzip
    data:
      compression: gzip
