---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres-17
  namespace: nextcloud
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: nextcloud
  backup:
    barmanObjectStore:
      destinationPath: s3://db-backups
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup
          key: accessKey
        secretAccessKey:
          name: db-backup
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 30d
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: nextcloud
      import:
        databases:
          - nextcloud
        source:
          externalCluster: nextcloud-postgres-17
        type: microservice
  backup:
    barmanObjectStore:
      destinationPath: s3://db-backups
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup
          key: accessKey
        secretAccessKey:
          name: db-backup
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 3d
  monitoring:
    enablePodMonitor: true
  externalClusters:
    - name: nextcloud-postgres-17
      connectionParameters:
        host: nextcloud-postgres-17-rw.nextcloud.svc.cluster.local
        user: nextcloud
        dbname: nextcloud
      password:
        name: nextcloud-postgres-17-app
        key: password
