---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: teslamate-postgres
  namespace: teslamate
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: teslamate
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: teslamate
  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
      - name: teslamate-monitoring
        key: custom-queries
