---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: teslamate
  namespace: teslamate
spec:
  configuration:
    destinationPath: s3://db-backups
    endpointURL: http://garage-backup.garage-backup.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: db-backup
        key: accessKey
      secretAccessKey:
        name: db-backup
        key: secretKey
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 3d
