---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: teslamate-postgres
  namespace: teslamate
spec:
  schedule: 0 10 2 * * SUN
  cluster:
    name: teslamate-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
