---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-11-29T23-40-49Z
    mode: standalone
    ignoreChartChecksums: true
    persistence:
      storageClass: backup
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cf.containeroo.ch/ignore: "true"
      hosts:
        - s3.local.${BASE_DOMAIN}
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cf.containeroo.ch/ignore: "true"
      hosts:
        - minio-console.local.${BASE_DOMAIN}
    environment:
      TZ: Europe/Zurich
    resources:
      requests:
        memory: null
    securityContext:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: minio-helm-values
      optional: false
