---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2025-04-08T15-41-24Z
    mode: standalone
    ignoreChartChecksums: true
    persistence:
      storageClass: backup
      size: 200Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: ${LAN_NETWORK_RANGE_V4},${LAN_NETWORK_RANGE_V6},${POD_NETWORK_RANGE_V4},${POD_NETWORK_RANGE_V6}
      hosts:
        - s3.local.${BASE_DOMAIN}
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: ${LAN_NETWORK_RANGE_V4},${LAN_NETWORK_RANGE_V6},${POD_NETWORK_RANGE_V4},${POD_NETWORK_RANGE_V6}
      hosts:
        - minio-console.local.${BASE_DOMAIN}
    environment:
      TZ: Europe/Zurich
    resources:
      requests:
        memory: null
    securityContext:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: minio-helm-values
      optional: false
