---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2025-09-07T16-13-09Z
    mode: standalone
    ignoreChartChecksums: true
    persistence:
      storageClass: backup
      size: 200Gi
    ingress:
      enabled: false
    consoleIngress:
      enabled: false
    environment:
      TZ: Europe/Zurich
    resources:
      requests:
        memory: null
    securityContext:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: minio-helm-values
      optional: false
