apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backup-mirror
    namespace: gitlab
type: Opaque
stringData:
    DESTINATION_ACCESSKEY: ENC[AES256_GCM,data:rgyuhNbyen+vgx2FkA==,iv:xk6+qMIoyIJ3w9ABjlAkaq+YRnejTZZK223Cfplz+Ck=,tag:i6++Sali4sNqmljz9kT2Yw==,type:str]
    DESTINATION_SECRETKEY: ENC[AES256_GCM,data:+JrqHQIPog7HvgEAP9FQKqeurRDnqOao1btNpWi+EvVN4NKtCXQvT+nVLfhIAC/57TNysTAHPZD3IX1I4gPeMw==,iv:WhdyKwuinRZmUChKIIKI2BQA7+uYq1gqBiAW8GtKmLs=,tag:bGXxoIO28MWa85cSVx7GuA==,type:str]
    SOURCE_ACCESSKEY: ENC[AES256_GCM,data:umlrIo+CIp4mkv3CZt8G+l8QdK42l5t8TqY=,iv:nAKq1vhHpqHi9cKPvkXc4TJip8gCKDJK9msRgy/QY3k=,tag:VT+Hm4F2dQWvz37x2etYfA==,type:str]
    SOURCE_SECRETKEY: ENC[AES256_GCM,data:UShq/igvh8RIkfGqw/2tDWn8Z0goByyW+OyBS0YwXTFHy8qrH5xE77/oe1vjhoglhLuCcjWFwrdeCSFkBZ9+jw==,iv:EIk1KtB/fwhx3RekAXLbuDdoCJyyW5V1nUbVnGQ9imc=,tag:kkZrFfIsOHV9V8DXt1HHwA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T13:22:53Z"
    mac: ENC[AES256_GCM,data:OxvGHFvvjDwxSTaKCwJdho0zkSkCp6FgnjV/n4+6iBx9Kk3icWmhucxPz4ihdd18EtROzeAUTpKlWrcf8HB5Qml62A7HxintWsLjXebe1s6kLug4CChNPOiSFuh5LFs+G1dLnp6mwELVey7ksZsquiISwBjD9foRu2XlpExhOWw=,iv:0PG1F7gMxDiuM8HcKgISQUYkND1Sfz0QMvpuf3CEWuc=,tag:HDCIaNSM4i6lyuC5bJpRBA==,type:str]
    pgp:
        - created_at: "2026-09-29T13:22:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//aLod88ABWzoT/90IxGn64OoyFYhQgAf76frPGcjs3JZ/
            mb2w63glyXb+W1b2TVtNC0nmzo3wuqktXvuT+7LGmLFIznfegHhgmA2NQomwDstA
            7dgXCe7CnKrKl2jQFdHmdlzEDEJNWj4dQt8WwfVmkN5D3PNKaYRmAu+RAnmobZIR
            8fn/yJv1LF6EHJgtBNjt8Qkzw0v5eCdEgcxzfzxBhTl+M+s/NNTN86dLRA9NRJDg
            8WrWRIHyKmqmeCIzwYAcY0D6ojlVZz1UL69kzufvZIUE/7WZVu44BkK8jGpjKhYt
            /9pQB0gUbKb7OtsrHwuv2ezz4DLiib3h1GqK0hHj/TGT0+t18/YQGMMBuEGVRVJG
            zNa/R7iRYmd/V6fUPdaVHBsYHlX7u74UORzxheVKuLBGRbLDPSnluyONQLrGy9Cl
            qt1L/T94TqGUTpJ7Rxgp5+3dMCRC7Ihjz5t9fMJO3Sci7hWo1lcFxGPRlxOf9QQU
            qV5txwi2EzxKRUcOr0bD+Uuh5Q+MyQVuFdVfqz6P8KZIL/0eAoS8gMFRGR+i3eoh
            XQEgzrPJPdOAeDlOC9zDp1n4o604tgdei+Z4fUqatBYl1iFdkpt1aELbMwAwrOw5
            NkVpn/KGjEhKI3Ofx55P4jC0ACZYssYQXpW3Qx+qSu01/DPLfySbw2kxOca7xp/U
            ZgEJAhA++TPPwlk73avQGQM/b/w2D22IQyISDemI7UhCuOBmjE8hUN7qAz8Di2bf
            WbHIQSAsoLwSnMNfFWwROj4WZdHlt6SRfaFIOsasr72lC76rIDkqOKZdEn5otNbf
            uVv2F5MqPw==
            =nTr3
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.3
