---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.7-1.0.0
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: immich
  postgresql:
    shared_preload_libraries:
      - vchord.so
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich
  monitoring:
    enablePodMonitor: true
