---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-postgres
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
      version: 0.4.3
    - name: earthdistance
      ensure: present
