---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: immich
  postgresql:
    shared_preload_libraries:
      - vchord.so
  backup:
    barmanObjectStore:
      destinationPath: s3://db-backups
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup
          key: accessKey
        secretAccessKey:
          name: db-backup
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 3d
  monitoring:
    enablePodMonitor: true
