apiVersion: v1
kind: Secret
metadata:
    name: db-backup
    namespace: immich
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:9Brsubwo90BNoA==,iv:EJPtaXi7XC4gtG6mcxsva+Ox0SYc8tbiFG1H7EL0NXI=,tag:jTeprkckAH1O4o4ozUoOFQ==,type:str]
    secretKey: ENC[AES256_GCM,data:DtlMuBMdxKMeyqvLpPm1oCRHNTb+7pTpCbn31eeJ+KVkxKzwiqYAaqTErJQQat5RGfsyeBXPkOcAz2f7hVEG6A==,iv:rWeiHo01qJ4EZEgv2ySDHQlxLtPhbq48htQ8sB3y9Jk=,tag:Y7JMMh+ek4u19H4udFU9ew==,type:str]
sops:
    lastmodified: "2025-07-06T18:33:17Z"
    mac: ENC[AES256_GCM,data:aUffs/JlsvmNZ2f5CJJrunvOXFcT6yjIJ8um14Z2fa89AHELRNb5v0Jo/TIy2WTh9/3DWbMA8vHDt9zMh2wB2+0qjeXpPQO/kwwfF5ly+tJOMlPGHiIoyO0CV9kDaM78wYen8GyUue2237uevcLEODyddnVoIg2+r5Xdu12Oyuo=,iv:kR9CD1Ju/qjZgSZdHvL2eCCTrZOKdMhC6asb4qIai4s=,tag:uYOQZWKFAPGOwek0j5lpKg==,type:str]
    pgp:
        - created_at: "2025-07-06T18:33:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAnJl2c6FLlj6LTHisCif2hXGdfRT169kEVvMhenXMjE/V
            zpO7vMQYAPYpkCQmtqYgC5S4BrYZPdTGl2TSruHrp8O/rhBysgQ+/sowbh1StqrT
            VSowutrKKltEkcxVZo69fCshu1JO0qbDtOdXC4KeJ1VPsiuzQ7NPVmWCd4/AXNmu
            ip/symTK3+X/QWxS0PM1HwR+IC3M0mFXOPYQ4rrHZHeSiE/q/B40miI6EfP+73Zq
            X1IfX7qJLBtvsukExNlQeKh4KjOKUm4pIMluvtVjq8sGKEYVm9r/Up+GtWqLGDfX
            lJCd0WRhgpfahSpJLvCn01q+3jK8QkkaizqOLPCQWbvmvTBHekyZb3hsfCNPj3eS
            bp1nEfFWfzK9jfwMpIMpCWAi0DdRf0aPahWwEUxdoCqiMRk6hIntb2JrLrhfmWxI
            LKujWrYntmqqDy4CVdYPDIbK/u+mvfu24pMAAgSxSFlAZFausiiBPc+zzIkbG5vE
            x8avyD2ponJubCKoU94kt2AlWJambDh3Yeo4UNAXK+IwGJT7yTDHXULpQvgGP3ne
            5l841JqDDm778uEaoouQbBKt1bPRyTIEmQk2IoOAKz5QbugB6DhB7eC5c+opLucP
            Vmgv7bjEJQxG9wgGOfXq9GEkgxPn8vSRg6dcFGQ5k91jUws9zbENW3bvfv1HFh3U
            aAEJAhBjX4vMYwzRMA6rjxskruzr4J83B/AGZQztGf3Fdyha44mKC9I12mh2Y0zh
            tJLCcWufkPqHRQZagIdT4UJGs48qrcoAbYKwcx01mBSwkEzVJHSSQ7z0/EeQPRdD
            j5C+M2LBrOYO
            =XMiI
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
