---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: falco
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
      interval: 5m
  values:
    driver:
      kind: modern_ebpf
    collectors:
      docker:
        enabled: false
      containerd:
        enabled: false
      crio:
        enabled: false
      containerEngine:
        enabled: true
        engines:
          docker:
            enabled: false
          podman:
            enabled: false
          containerd:
            enabled: true
            sockets: ["/run/k3s/containerd/containerd.sock"]
          cri:
            enabled: false
          lxc:
            enabled: false
          libvirt_lxc:
            enabled: false
          bpm:
            enabled: false
      kubernetes:
        enabled: true
    falcosidekick:
      enabled: true
      replicaCount: 1
      config:
        slack:
          minimumpriority: notice
        loki:
          grafanaDashboard:
            enabled: false
    tty: true
    customRules:
      falco_rules.local.yaml: |-
        - macro: user_known_stand_streams_redirect_activities
          condition: >
            (k8smeta.ns.name="gitlab" and container.name in ("gitaly", "gitlab-shell", "gitlab-workhorse"))
            or (k8smeta.ns.name="flux-system" and proc.name="gpg-agent")
            or (k8smeta.ns.name="renovate" and container.name="renovate")
            or (k8smeta.ns.name="ingress-nginx" and container.name="controller")
            or (container.name="postgres")

        - list: user_known_packet_socket_binaries
          items: [speaker]

        - macro: always_true
          condition: (evt.num>=0)

        - macro: user_known_contact_k8s_api_server_activities
          condition: (always_true)

        - macro: known_drop_and_execute_activities
          condition: >
            (k8smeta.ns.name="gitlab" and container.name in ("gitaly", "build"))
            or (k8smeta.ns.name="usenet" and container.name="sabnzbd")

        - macro: user_known_read_sensitive_files_activities
          condition: >
            (proc.name startswith "python3")
            or (k8smeta.ns.name="gitlab" and proc.exepath="/kaniko/executor")

        - macro: allowed_clear_log_files
          condition: >
            (fd.name startswith "/var/lib/rancher/k3s")
            or (k8smeta.ns.name="gitlab" and proc.exepath="/kaniko/executor")

        - macro: user_shell_container_exclusions
          condition: >
            (proc.cmdline contains wal-archive)
            or (proc.cmdline contains wal-restore)
  valuesFrom:
    - kind: Secret
      name: falco-helm-values
      optional: false
