---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-17
  namespace: keycloak
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: keycloak
  backup:
    barmanObjectStore:
      destinationPath: s3://db-backups
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup
          key: accessKey
        secretAccessKey:
          name: db-backup
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 30d
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  storage:
    size: 20Gi
  bootstrap:
    initdb:
      database: keycloak
      import:
        databases:
          - keycloak
        source:
          externalCluster: keycloak-postgres-17
        type: microservice
  backup:
    barmanObjectStore:
      destinationPath: s3://db-backups
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: db-backup
          key: accessKey
        secretAccessKey:
          name: db-backup
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 3d
  monitoring:
    enablePodMonitor: true
  externalClusters:
    - name: keycloak-postgres-17
      connectionParameters:
        host: keycloak-postgres-17-rw.keycloak.svc.cluster.local
        user: keycloak
        dbname: keycloak
      password:
        name: keycloak-postgres-17-app
        key: password
