---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: renovate
  namespace: flux-system
spec:
  interval: 1h
  url: https://docs.renovatebot.com/helm-charts
  timeout: 3m
