---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  interval: 30m
  url: https://christian-schlichtherle.github.io/synology-csi-chart
  timeout: 3m
