---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  timeout: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  values:
    env:
      REDIS_HOSTNAME: immich-valkey.immich.svc.cluster.local
      DB_HOSTNAME: immich-postgres-rw.immich.svc.cluster.local
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-app
            key: username
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-app
            key: dbname
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-app
            key: password
    immich:
      persistence:
        library:
          existingClaim: immich-library
    server:
      image:
        repository: ghcr.io/immich-app/immich-server
        tag: v1.143.1
      ingress:
        main:
          enabled: true
          annotations:
            cloudflare-operator.io/content: ${BASE_DOMAIN}
            cloudflare-operator.io/type: CNAME
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: pics.${BASE_DOMAIN}
              paths:
                - path: "/"
    machine-learning:
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        tag: v1.143.1
