---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  timeout: 20m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  values:
    valkey:
      enabled: true
    immich:
      persistence:
        library:
          existingClaim: immich-library
    controllers:
      main:
        containers:
          main:
            env:
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: host
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: user
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: password
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: dbname
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.3.1
    server:
      ingress:
        main:
          enabled: false
