---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: immich
  namespace: immich
spec:
  podSecurityContext:
    runAsUser: 0
  backend:
    s3:
      bucket: k8up-immich
  backup:
    schedule: 0 1,13 * * *
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
  check:
    schedule: 0 3 * * *
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
  prune:
    retention:
      keepDaily: 2
      keepLast: 14
    schedule: 0 2 * * *
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
