---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  HOST_IP_V4: 10.0.1.100
  HOST_IP_V6: ${IPV6_PREFIX}::100
  LOADBALANCER_ADDRESS_POOL_V4_START: 10.0.1.200
  LOADBALANCER_ADDRESS_POOL_V4_STOP: 10.0.1.210
  LOADBALANCER_ADDRESS_POOL_V6_START: ${IPV6_PREFIX}::200
  LOADBALANCER_ADDRESS_POOL_V6_STOP: ${IPV6_PREFIX}::210
  LAN_NETWORK_RANGE_V4: 10.0.0.0/23
  LAN_NETWORK_RANGE_V6: ${IPV6_PREFIX}::/48
  POD_NETWORK_RANGE_V4: 10.1.0.0/16
  POD_NETWORK_RANGE_V6: fd01::/48
