apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:7irhDB3E,iv:LiViGoBHoLxQuJz89lOMemIM7K9po10ygzfnYunDtaA=,tag:Fj0goguzHKScoTEW/w1WLg==,type:str]
    EMAIL: ENC[AES256_GCM,data:VfulnzVRhIXlcKPU0XKzStn0B/I/5g==,iv:RfppDNRt/cBKBRhRGIs8ZO6gsROySMNLQiZYPqt1i5I=,tag:Eq5+4IppvgJgkOiuUOt9+A==,type:str]
    IPV6_PREFIX: ENC[AES256_GCM,data:2szuuSYfVrmbmMnbdg==,iv:NmyjaOPrlPHzWKQrH1b/jGNPyiIOhY2YzaeVf0hhw/E=,tag:65YvS77XiQY0I+FE1PTAbg==,type:str]
    MAIL_IP_V4: ENC[AES256_GCM,data:7waLMUCDa3RATT6qgsQ=,iv:UOPPxGGHXHsr0KgOQAQlDLkJTYNhuNIP75TVeKcEzAM=,tag:IH+wtBtEwI70gkeX0wp3gg==,type:str]
    MAIL_IP_V6: ENC[AES256_GCM,data:6dUnh1svCbwAIXTI1DHV2ChrRsc=,iv:U/hi0i2+erKKnJc8v661O3ndVQ2BbqC7xvaq39rzQgM=,tag:c/y2WrDTdDqJ3+dLx8t8zQ==,type:str]
sops:
    lastmodified: "2026-04-14T14:11:48Z"
    mac: ENC[AES256_GCM,data:aNZcE1V6i7J1LyqJfPHBUFH9EhJg+4IzqbxEKNeao+g6rSYO2SaDC0rQoPfzFuqXt2YEd5O5Vs6ScgFqmORUsp2Tf9N51sCEUjfeAvRpXWiNlo/JrcHMrcQfKXGKvtb4QAh4Bb4ROhBg8eirrhja8VjiSMb86GA7JeZkfK7PEh8=,iv:h7rkq7rYZpg/7yKXVpLJJRZIoc78DfYwYQ2VRuIYlI4=,tag:tHN6XNkHhsBDTDjRWQ4qKQ==,type:str]
    pgp:
        - created_at: "2026-04-14T14:11:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAoxULVTYjyGip3tA7NsCV3xe00YvPgAcV1vyw+9Vy4kD+
            O4egHJL43kUR6vKYxRSF4M2AvCfk9CfCPY8uvWts5P/NBU2q5spfLdU087oSOEWm
            CLScMgP1RtY7l9PB9SUIlUqpcQSO5FGmuYE1xt2zL7eZVsT3e55qBb6H4xlw6Pf9
            /VFbpwaEy0d+lnFgywstqSUVOIul55fMfGEH5r5wCBWjbwYpeJJfVrHUHB4P1tcP
            S6BhQvmIyUElt2E0hRem8eSpussK3SsSCZRpTSsRlhDtljAy6s5OQCrutLtVr8VD
            ja2tKWiGbGLiWb3U2AyxjVoCh7ac4IpwVQRo9dglCUmSNjDR8yndt4ggctLLENG+
            E1rSRIVV/txQMvG54HtwE6cRMkHIN0dE2WWoX8t3KI7f9qo8/DWjPuYrWOEhRfr8
            05yjL0E5nsEFCXgPWSetWyxFV9aFgzE+AI1AsyZmLfAlFdEl0YQ1SF9RUhPKbSHx
            BTBZTNTyddv675q6fif6/V3NsHjQOoLtutOj8njs/qHjRELZ4a4YJc8VNNIpsnyL
            kZLZzIuI68FUK2VEF48QjDaLWS3l+rxfwPiqnzDlg1orTT/RNx5BJMOXSybSKX31
            V3tW7LM8oxWhpmP71ouM5uqmGmUv3Q9ZPnvHgQYTQ3phRkxOs6KEQTQNAP+znafU
            ZgEJAhBCjnmJdY4783H3LxA63ch4h/88tLBA27PsNc7+f4x9IRvC1c3wPt9WoOqT
            bJAnGRwYimJI1CwcS/aBYkWAshI+lZroQLRCEDepn9KqrkW+Sk0WHkjNLpvnf4Lc
            cNJ4hOlu1w==
            =lfhC
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
