---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
  annotations:
    helm.sh/resource-policy: keep
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: backup
  volumeMode: Filesystem
  volumeName: pvc-6dd8b2cf-0d61-4dd4-8670-df18200ec046
