---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: envoy-gateway-internal
  namespace: envoy-gateway-system
spec:
  endpointSelector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: internal
      gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  ingress:
    - fromCIDR:
        - ${LAN_NETWORK_RANGE_V4}
        - ${LAN_NETWORK_RANGE_V6}
      toPorts:
        - ports:
            - port: "10022"
              protocol: TCP
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
    - fromEntities:
        - cluster
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: envoy-gateway-external
  namespace: envoy-gateway-system
spec:
  endpointSelector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: external
      gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  ingress:
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
    - fromEntities:
        - cluster
