---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  path:
    escapedSlashesAction: KeepUnchanged
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
