---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-geolite-db
  namespace: envoy-gateway-system
spec:
  schedule: 0 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: update-geolite-db
              image: ghcr.io/containeroo/alpine-toolbox:3.1.1
              envFrom:
                - secretRef:
                    name: maxmind-license
              command:
                - /bin/sh
                - -c
                - |
                  set -eu

                  WORKDIR=$(mktemp -d)
                  trap 'rm -rf "$WORKDIR"' EXIT

                  download_and_install() {
                    edition="$1"
                    filename="$2"

                    echo "Downloading ${edition}"
                    archive="${WORKDIR}/${edition}.tar.gz"
                    curl -sSL \
                      "https://download.maxmind.com/app/geoip_download?edition_id=${edition}&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" \
                      -o "$archive"

                    echo "Extracting ${edition}"
                    extract_dir="${WORKDIR}/${edition}"
                    mkdir -p "$extract_dir"
                    tar -xzf "$archive" -C "$extract_dir"

                    db_path=$(find "$extract_dir" -name "$filename" | head -n1)

                    if [ -z "$db_path" ]; then
                      echo "Could not find extracted $filename file"
                      exit 1
                    fi

                    echo "Replacing ${filename} in PVC"
                    cp "$db_path" "/data/${filename}.tmp"
                    mv "/data/${filename}.tmp" "/data/${filename}"

                    rm -rf "$archive" "$extract_dir"
                  }

                  download_and_install "GeoLite2-City" "GeoLite2-City.mmdb"
                  download_and_install "GeoLite2-ASN" "GeoLite2-ASN.mmdb"

                  echo "Done"
              volumeMounts:
                - name: maxmind-db
                  mountPath: /data
          volumes:
            - name: maxmind-db
              persistentVolumeClaim:
                claimName: maxmind-geolite-db
