---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-geolite-db
  namespace: envoy-gateway-system
spec:
  schedule: 0 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: update-geolite-db
              image: ghcr.io/containeroo/alpine-toolbox:3.1.1
              envFrom:
                - secretRef:
                    name: maxmind-license
              command:
                - /bin/sh
                - -c
                - |
                  set -eu

                  download() {
                    EDITION="$1"
                    OUT="/tmp/${EDITION}.tar.gz"

                    echo "Downloading ${EDITION}"
                    curl -sSL \
                      "https://download.maxmind.com/app/geoip_download?edition_id=${EDITION}&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" \
                      -o "${OUT}"

                    echo "Extracting ${EDITION}"
                    tar -xzf "${OUT}" -C /tmp
                    find /tmp -maxdepth 3 -name "${EDITION}.mmdb" | head -n1
                  }

                  # Download City DB
                  CITY_PATH=$(download GeoLite2-City)
                  if [ -z "${CITY_PATH}" ]; then
                    echo "Could not find extracted City DB file"
                    exit 1
                  fi

                  # Download ASN DB
                  ASN_PATH=$(download GeoLite2-ASN)
                  if [ -z "${ASN_PATH}" ]; then
                    echo "Could not find extracted ASN DB file"
                    exit 1
                  fi

                  echo "Replacing City DB in PVC"
                  cp "${CITY_PATH}" /data/GeoLite2-City.mmdb.tmp
                  mv /data/GeoLite2-City.mmdb.tmp /data/GeoLite2-City.mmdb

                  echo "Replacing ASN DB in PVC"
                  cp "${ASN_PATH}" /data/GeoLite2-ASN.mmdb.tmp
                  mv /data/GeoLite2-ASN.mmdb.tmp /data/GeoLite2-ASN.mmdb

                  echo "Cleanup"
                  rm -rf /tmp/*

                  echo "Done (City + ASN updated)"
              volumeMounts:
                - name: maxmind-db
                  mountPath: /data
          volumes:
            - name: maxmind-db
              persistentVolumeClaim:
                claimName: maxmind-geolite-db
