---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-geolite-db
  namespace: envoy-gateway-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  schedule: 0 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: update-geolite-db
              image: ghcr.io/containeroo/alpine-toolbox:3.1.1
              envFrom:
                - secretRef:
                    name: maxmind-license
              command:
                - /bin/bash
                - -c
                - |
                  set -eu

                  echo "Updating MaxMind GeoLite databases"

                  mkdir -p /tmp/maxmind-city
                  echo "Downloading GeoLite2-City"
                  curl -sSL \
                    "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" \
                    -o /tmp/maxmind-city/geolite2-city.tar.gz

                  if grep -q "Daily GeoIP database download limit reached" /tmp/maxmind-city/geolite2-city.tar.gz; then
                    echo "Reached daily download limit for MaxMind GeoLite databases. Skipping update."
                    exit 0
                  fi

                  echo "Extracting GeoLite2-City"
                  tar -xzf /tmp/maxmind-city/geolite2-city.tar.gz -C /tmp/maxmind-city

                  CITY_PATH=$(find /tmp/maxmind-city -maxdepth 5 -name "GeoLite2-City.mmdb" | head -n1 || true)

                  if [ -z "${CITY_PATH}" ]; then
                    echo "Could not find GeoLite2-City.mmdb in extracted archive"
                    exit 1
                  fi

                  echo "Installing City DB to PVC"
                  cp "${CITY_PATH}" /data/GeoLite2-City.mmdb.tmp
                  mv /data/GeoLite2-City.mmdb.tmp /data/GeoLite2-City.mmdb

                  mkdir -p /tmp/maxmind-asn
                  echo "Downloading GeoLite2-ASN"
                  curl -sSL \
                    "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" \
                    -o /tmp/maxmind-asn/geolite2-asn.tar.gz

                  if grep -q "Daily GeoIP database download limit reached" /tmp/maxmind-asn/geolite2-asn.tar.gz; then
                    echo "Reached daily download limit for MaxMind GeoLite databases. Skipping update."
                    exit 0
                  fi

                  echo "Extracting GeoLite2-ASN"
                  tar -xzf /tmp/maxmind-asn/geolite2-asn.tar.gz -C /tmp/maxmind-asn

                  ASN_PATH=$(find /tmp/maxmind-asn -maxdepth 5 -name "GeoLite2-ASN.mmdb" | head -n1 || true)

                  if [ -z "${ASN_PATH}" ]; then
                    echo "Could not find GeoLite2-ASN.mmdb in extracted archive"
                    exit 1
                  fi

                  echo "Installing ASN DB to PVC"
                  cp "${ASN_PATH}" /data/GeoLite2-ASN.mmdb.tmp
                  mv /data/GeoLite2-ASN.mmdb.tmp /data/GeoLite2-ASN.mmdb

                  echo "Cleanup"
                  rm -rf /tmp/maxmind-city /tmp/maxmind-asn

                  echo "Done. City and ASN DBs updated."
              volumeMounts:
                - name: maxmind-db
                  mountPath: /data
          volumes:
            - name: maxmind-db
              persistentVolumeClaim:
                claimName: maxmind-geolite-db
