---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal
  namespace: envoy-gateway-system
spec:
  ipFamily: DualStack
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.0.1.201,${IPV6_PREFIX}::201
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external
  namespace: envoy-gateway-system
spec:
  ipFamily: DualStack
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.0.1.200,${IPV6_PREFIX}::200
