---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: envoy-gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: internal-http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      name: internal-https
      hostname: "*.local.${BASE_DOMAIN}"
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - name: local-${BASE_DOMAIN/./-}-tls
            kind: Secret
