---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: metallb
      namespace: metallb-system
    - name: cert-manager
      namespace: cert-manager
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
