---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  dependsOn:
    - name: metallb
      namespace: metallb-system
    - name: cert-manager
      namespace: cert-manager
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  values:
    config:
      envoyGateway:
        rateLimit:
          backend:
            type: Redis
            redis:
              url: envoy-gateway-valkey.envoy-gateway-system.svc.cluster.local:6379
        extensionApis:
          enableEnvoyPatchPolicy: true
          enableBackend: true
