---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maxmind-geolite-db
  namespace: envoy-gateway-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nvme
