---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: usenet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          image: ghcr.io/linuxserver/overseerr:v1.34.0-ls138
          env:
            - name: PGID
              value: "2000"
            - name: PUID
              value: "2000"
            - name: TZ
              value: Europe/Zurich
            - name: DOCKER_MODS
              value: ghcr.io/themepark-dev/theme.park:overseerr
            - name: TP_THEME
              value: catppuccin-mocha
            - name: TP_COMMUNITY_THEME
              value: "true"
          ports:
            - containerPort: 5055
          volumeMounts:
            - mountPath: /config
              name: data
          startupProbe:
            tcpSocket:
              port: 5055
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5055
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: overseerr-data
