---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: barman-cloud-plugin
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/cloudnative-pg/plugin-barman-cloud.git
  ref:
    # renovate: datasource=github-releases depName=cloudnative-pg/plugin-barman-cloud
    tag: v0.10.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/config/crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: barman-cloud-plugin-crds
  namespace: flux-system
spec:
  interval: 5m
  prune: false
  sourceRef:
    kind: GitRepository
    name: barman-cloud-plugin
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: objectstores.barmancloud.cnpg.io
