---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: envoy-gateway-valkey
  namespace: envoy-gateway-system
spec:
  serviceName: envoy-gateway-valkey
  replicas: 1
  selector:
    matchLabels:
      app: envoy-gateway-valkey
  template:
    metadata:
      labels:
        app: envoy-gateway-valkey
    spec:
      containers:
        - name: envoy-gateway-valkey
          image: valkey/valkey:9.0.0-alpine
          env:
            - name: TZ
              value: Europe/Zurich
          ports:
            - containerPort: 6379
          startupProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
      restartPolicy: Always
      automountServiceAccountToken: false
