apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ChBYcBBkspdjcFx2Q8pJvNUOxl+zzuhKKbP0JzHySsDFpMfUy1ttL4f7hoh4fMY15eIuUJfOW+Hqmy+9p02UyVxHSQSmfH3Eumn406UtuWRW5ny7DR9IT81KiA8X,iv:GAZCoQN/0YBWXNJEM5iNIFCRpDSN19tWrIxg59uOSzs=,tag:QkgHWz9a8kLkIzO2qehKyw==,type:str]
sops:
    lastmodified: "2026-03-31T17:31:29Z"
    mac: ENC[AES256_GCM,data:Z2G7ij15cpU7ST4U4n2u7TLdujriNDrJXQx3WYZTrpcHXdrDgrFyeC2NZ/GjJxgESsIUQL5XdkuQhJ6SodyQGX3yrxFm24SXE51FC9GAxUdCWr1LMtSx6GrLTapfDfx5F5minDSlHJ744NbRw4NohyiNC2N2oBhWRXxIxeiZ5Ls=,iv:EwOJRPD6QHA2imFi4EmdGMAqpGEd0sjmax2pPRgpNhM=,tag:JhLWYdwhXJt7o1KncQ2ZkQ==,type:str]
    pgp:
        - created_at: "2026-03-31T17:31:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//Y7Dxz5QChHc7NVyYo9zsxUmEcxcIHwkcvENO2Ule+8aC
            Sr+SIYRi+ojQQY4qwhM1QnN5AhuS1dAa6pwFoAAMYzEEzy586TRxexzJoU0fqiSW
            acMCUt4/XtKPUQr0jc6B3baHjJBmds2Hcw/1N4VFzh2CCnJ63ZSlbd9pCskITo/D
            zkad+YroeGgTz5Sj3QqnA236l3iiFfobBFQHnHHOhLkAeQFf7ASvZ4LLJLEgSarN
            FSvD2B5irYYDAAWigjO+VzWdzVdc745ngDFJ98INN2F6c9A56kNbCJdQMNqbKnMg
            RP+8FUY6pgM5mbH6uXTAYvEnhI/9bK3/XaOGPU1Thzf0KJ5a+ZYBmHuF7zHACPOI
            BuHPfjosbVdeTE8NaW9EnyxgxE80tONVUCHONO4x7YhxYQTOjR2+uGA7kgM/miBY
            Rh0qpDv1vJtbqIRvZhgR2rZS10hM1hXyJASg+LwCH6ePKPxKXAe/G3UJky/Y5ztF
            NBnunPwKKoQKf9PBlytFAh80aquyFT/JtDQdJsefqYl4OmvYqCxsJmp7qS1yIKzx
            Hg9IOxeAT3TCp2tjAYGV69azKLQE9GPkmPkrglm4SrMuJrw60oeeLyVGt6N1cQWD
            tY9/Ovr0la6b2YVViLw7toE0KQ1e9rdb1dI/mvFWcvl9UWEtzSLp5lZvNl1rtnjU
            aAEJAhBhJtae5B1oWukKw0gdYIYI6W+xgg+ypsLIjdstH3kNCbvSDi+N/q2U6gpX
            a6KIefIs7+v2vzGWjirfTPW135kW+UVYpbDGq9DdFF3eGFwVLYCWRIY29wcg3RvX
            9DfXEvKsUxZG
            =1G/2
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
