apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:WWgaHqDWX2BB4WdKnhiFf/7/gvSzo2aHPu0gYM6OkOSLv9bRLa/WgntlXYlL1a0qhY0iAQ0cAvV4lvr519ARa2O3X/1iwHNPA+misLx2CVjpKErOJH27nPl6Ooam,iv:+jyZQM57YOtSnMTNVhkEogS+WHKK4Aqoa63EmgLf4u4=,tag:VgJJzYCioCtXmLgDoJLxEA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T06:11:36Z"
    mac: ENC[AES256_GCM,data:y+lmjh+f9Ucr25vyKGEGwIJ7Zwvraeq0EeH+hX+Df55Gt/CIyLxIrGrcZoYTO1r92wA8FkQf3WLnbv6NalzdyZmyXO0XgPAwKxmDqtnaNblFJi1ELb34n2gFzDhOt9mbF0UugU0csde4ktxiBjTpicL/V0EztuVEZjuuZSlC7TY=,iv:BFmDZZpMnueHLt4bOZJZVqC1b5wAFUHVLfIxNzfZcTs=,tag:ERbfNiMix/ZrNzuasiJY5g==,type:str]
    pgp:
        - created_at: "2026-06-29T06:11:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ/+LYh9/tvySulNfIxZIFR6AljhUT9dmo+Nu6S3j0RXhom6
            /ESmRlvrlh33xEjAZGsASbWz6uxHiYnEHyOtelM9Qi0rY6xm3YY4JkL2uYD4GdRr
            Zt98xH/BO1Ow0fG2ltzRBAYf6b16RX9hu/YXuKgT3n0oORujVcev+yXhaVlkV5Ox
            CQnlgOfb3uoD6oQ9UBr5yv7zvPfwtpTAtGh6W5VPLuLS0B/mOyr0T/8kXN1Mkmz6
            ZQN5Q2rb9tnr+yNpMMnE7xHzcjEoSwXXi93p17+L4Jm2A3bYIYcCD1r3if6Q36dv
            T0us+yEdHHbnUoqtiC55IoydaEYvw78WTS1e7V7XknDFJeVsiqpaZqBJQhQOpetZ
            QwnolYlN8v9wdKKn9ReJBZal4ylOtqHDoXavLfRUnT5gcsQdOjJzuGf/pez6RTvM
            JYeZRtGbQ+IfT3AkofCfUhWu715HpAtlJ/e9UY4fpcSp0p3ZxA7FRJF0YJb+Fp6r
            AbLdlU3dwzt+fBCiTMVCInoqlQhi2Efi26mMcEFxdK4g2yvkaOAFldTbnOf3aS4h
            Hd1uhY/B2BhlzVs9OJTBUc1jqDtfOuM/KsjRIQHoq8eMe1i9xh/X+8Bo39h9triP
            L/W3ZWHVajUeT8WqN17Tc5BRicLqJxTvbowpTeuzOaFEmGlRfA1ugeBkHQWA0JfU
            ZgEJAhCGAUtS6Cj8Qo9go3XwDyF2cL+2zl52uEsRJWSYg4wJR9dRSzfTEz53zexT
            Uf2cILba4bbO84sxvnGYpxIMzagj8rfGIBUv/jmSFH8wgVvJawtgSSM5UBwMsSWh
            Y7h316bswg==
            =YVqQ
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.1
