apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:0rkQuNokK4Z/KHzLQedCjPP2rB4BFfwsQZ9Twix1b9+kIaQLDZuPTw==,iv:X4Z01Y8yrFaVFNcWt6xz1I35GgXjhJWvVqMI5fxYyqA=,tag:cd5cvX99z/x8zJOPrmlLig==,type:str]
sops:
    lastmodified: "2025-07-18T06:37:17Z"
    mac: ENC[AES256_GCM,data:b5fQ/tdp3awrlUasAhhn6jnFbnrnRDMRK/+eRQ2QhKCJoNVIXHpGQdqn0vltOiok4uZ/QTOG3oVXr29NRVujv6nRL2z8P+NumksXAFQT1bk6iJvVqXorSMpfcTzUNpEl83cgWEbyARaiulGNB3Rs1EWIHUuBt4kfgNUZpyHVgWs=,iv:dqQrGRxixrHZJOL5CWOtbG4fnfc/ilfs6QeDLtvG8oQ=,tag:q6x2G37x0PCbQLIGDkLYRQ==,type:str]
    pgp:
        - created_at: "2025-07-18T06:37:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAmlNN1azzmjLqGya2iSeZ/InP6KRHvzg3mLnlRA8Xh7fQ
            +uD4Q5bciZnAFK88oV66Ovzhb4+rdHWy0KtECFTW+C+uhkI+jypiRUGclg78NwRP
            yvfoF/+vfaxWlD+63XRtwAX8gAhfYIO5IdOeNl9c3u+RHT7nrjgwH5oaGhchxZYY
            PGE9D+0X31UjYn5c4y0Bly/mkzfzC6aqMsRS9nSmalaH822ynti/6YzajFS+Lwgo
            zwHCFv+viM7BBDDdJ0vOA7f7m6W+q+PKHprYqcVVOe8hBQYQqadEISk7fvDHZVGX
            U/zQs37bgFUi1y6hGMf3EioNFrTFq1VU4ImFalk8qZ0tsEnQD3GKtN/LE/mzQY++
            RKxfsdKZRzt5z8tDMIcNTwESmBUnhuYCV4j5uYt+l/FbSVEKb7zlfgakx9fgl5l+
            XoLDlFu/6NuL+d/Z48kr9ZySXQsNoUMa0xSjWfY1F/ooy5E34kS6VCcRGOF831F8
            zzcX93NGeQumIQQSrKiGlexqYkGINqTcqLcCwtU5/HZdEy9rJw5ckcHgpxgVYuMC
            pNxgiC92zs+xXyefPXLc9NpDGh6F09/Aw7NHhBIkkheg6q+yBTBR7pZ0Gn7xVaNZ
            kEE+CfgTA46+7MqQpTChO1vR/h7pdhth28gwHP6GzRUb8dKO8/C8jGvdiZIJF+/U
            ZgEJAhBhNzKNUR1rYpmx/JIgybRrw1scWnwwodFoQack3MouBF4feYCzlTcA4/Zm
            0v9ECWFzt27k6+XrIbj7S5HdtQy4CDfk3XRdU2YBxBe1Ix+A2b4wQVzj7Hlg5Wxg
            ekEkXy/TeA==
            =oeaC
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
