---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cilium
      version: 1.16.7
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  values:
    envoy:
      enabled: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/whitelist-source-range: ${LAN_NETWORK_RANGE_V4},${LAN_NETWORK_RANGE_V6},${POD_NETWORK_RANGE_V4},${POD_NETWORK_RANGE_V6}
          hosts:
            - hubble.local.${BASE_DOMAIN}
    operator:
      replicas: 1
    kubeProxyReplacement: true
    k8sServiceHost: k3s.srv.${BASE_DOMAIN}
    k8sServicePort: 6443
    nodeinit:
      enabled: true
    nodePort:
      enabled: true
    ipam:
      operator:
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv4PodCIDRList:
          - ${POD_NETWORK_RANGE_V4}
        clusterPoolIPv6MaskSize: 64
        clusterPoolIPv6PodCIDRList:
          - ${POD_NETWORK_RANGE_V6}
    ipv6:
      enabled: true
    bpf:
      masquerade: true
