---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
