---
apiVersion: v1
kind: Service
metadata:
  name: garage-backup-admin
spec:
  selector:
    app.kubernetes.io/name: garage
    app.kubernetes.io/instance: garage-backup
  ports:
    - name: admin
      port: 3903
      targetPort: admin
