---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage-backup
resources:
  - helmrelease.yaml
  - secret.yaml
  - admin-service.yaml
  - provisioning.yaml
configMapGenerator:
  - name: garage-backup-provision
    files:
      - provision.py
generatorOptions:
  disableNameSuffixHash: true
