apiVersion: v1
kind: Secret
metadata:
    name: garage-backup
    namespace: garage-backup
type: Opaque
stringData:
    rpcSecret: ENC[AES256_GCM,data:Un+Ck5wek5TwqzcYKpl0nf5Osy31+xe0yJ0KxyXf3oAZcR78RQ+Skyf4dge+DDA1nqFZX8CsC3PBmXYc9+W3Iw==,iv:8E5aEFsGl7/tJo6zr4wUmYPfNrdV2NBdNV1e7BEhh90=,tag:4J1mRvfRCi8sc7MNvURcTg==,type:str]
    adminToken: ENC[AES256_GCM,data:kP5/MCKwsj3oGmSYZjAmdJ/f+KV5sIJXooui1E3PGkK3MlbmGY15xRsmy9Ig+XEfebZT77Hnw90KBZnXrx8jAg==,iv:echAzLUEOox/OPCgu19RaVPR8bS8fT8pvLyQTLPEbqs=,tag:gcnT9XZbft1NWttzCOQAWQ==,type:str]
    provision.json: ENC[AES256_GCM,data:tOqQ59va9hQn20gS1uAlb9mqXfCHYxweVDtwMgX008gUOhmWOk0pixE9nl95je7VmCAXAxUpqoMepe0ky3lD+vr5R93SXfuUJM4hbtjFGI8C3fj96dwcFdFa6fyWXptM0/qw03ZM3qthT7U0LKYpW6hZcj6OEU4jf6syOe/W38ISfBsXRBpcg2Ce4CJWFxWmfdzETQZ1HX+jWR+ISQSODCgQYU2xbu3NY35UIB9QZKrVphzjSkixVvE6rbHJe/lJdzvvvaImhjJhDQY8PQaTuLva6Nq07cComdmB+hFMt+GBzafi3ERmjagpbg2czIHuFu/t/6W4xiFmsa8wJywbvRR6C+cwBjVtc1fQRnZrcioYn3CLpSxDVvIlDuh+V1j3N2+eLUqQvrRTgZ/+FM/XXrtpIxlLcgYBUMs8NZIGG43J3tzpIzugYZiuOHEAutCZmB1M7H5CTr5PdwiqL1VgtmxZYpPaKqFn7SkYTikN+x5+T/QD7uG7xIn2hYoaAePJ8q/emXevhwpHuhtUZcvXk8rv82ujIelk0IvIIRVJ/xb6ECWU/aNFWobKQNAqoPyPNvUN2/XISdqni2r8E0td3+sDfFHrnjtwWIX3bcevuwH61Pl7EtVxh8Q1YtEmuMVMl962AQQXZcHr08Pf2R6a0YwcFEHVX0EDunB6OIbLOXhMy1dpRR+iEOQLzNc36ta0nvannbJ8VsLl6G/bAth5XIMiMfmlI20XIeUmPw5cTVt5dPrtyWt7GwnBma5QyTpwNabWSENPn7zIuAa1eRmctFyr46gbC9j+7OmIIGXSfy5FEJlbP0KVoXsg7xI+rcaL8cNhwWvrYVPGW4cuSwjLJ5trMVzac/YyXJv7AmHeYVjXpWnAfF2qC9kiFWpGc1RQi6p1n8f+fxjeJaihJyR98n7dLIENhisfwYU//2rWsqvFvmn+w2h0m3M7o1f0emC53jna2xdjqhMzLShic6/CMY39y8PymtSFgdS7MBFEVUACAq79OPuYUD0oaTYMvdjdG30Xyl7utiWGige9o59eHeHv4aBsHn8gLhq2qvN/FN/LG+6nnMPzSf6dKpLJxybxwdJRZClenHH80HK90lIDnigvrHAq9XLO5XzQxAGGEnGNZW2//cuiB3SDluiXY2ECmYOiEAfYsSH54vLELgcMjLuN8bjDU72pJLO5MEiF/LWUyPjXWifDQwPWc+BlouN+ajd1Wqaoyg7q0+XaHOeHaaW2Eg1lKsQgYNPU5U76ZXQolL4PbxS9SjJhEmGIB53L5+a0grtE97Aj1iRuncbQmVBlOIWsLUjd0u+wWano+wTVun5IUJguhg8jZ4N9tnIHXB190bq2X/dCzQVosaXFgaOoU4vZFOuqcgsMJvMl42HCtjHkNK84oYluBYQYEjP093fCIfn51yTjwO6nXFcfJCDB3QpbquPqMVF8W6fibwNezFYXWJdNDzo6m2p1UG05Z7bIJtkDXJTziUwPH7ayOpjcrrltnH00bEvlMhmxRSQRFQtsrxFhmW/gE3Q3I2zVjMmebfEdmzTAp1hcQ+dsLb4WGbQmWm/T1jBJkF+xUx2ZXtcH7fSg8EeU824muVYYcto3p4+KHhAeLgGj/djxzjgGSbYXIwCR6OLuYuLAAHaKrR2YxYM/WI6WYSxz44OlWOQ60ENeg0NJ2RQ4y8X/2vJoG2qqblppvK8VQ6MN2zBMHvr0jkaS/nYMjv7iH+PRLXHACsFvtojBRUTQCYn1tetzoLs34VD/A2vuPvUUE+oBHnScazIQG7FmXm2+9iErtQGU7KlRAyNPxOIBI6U1U0nJE3goYXD3jyKlVP/TLQVO757C80mKt1QPgwdpAPrTLnAg3Ef5id1U344fps6e73l+jhBaT3Mj6/UBu7BoLwniy72mVUtbN52j4DWsgUupDn1eJEb4bw1MOAuDYIlGZTUzUMDq0H0wlDpREk93oVuGI+L+Mwn+oDy1V+wU7RRRpjFS/emVDrfcsGFxVn8p14+gzze/6GsZJZFeX0D86qDu+nlwlJvQnXGFoHX20H/BowbHZx3YM6saA1BLenMKWtBsxEvCpCwtxVX9QwHV5WFRbqfeyRZg8/T3Nlkj7nBX1r7cHCJzOmfdhzSMXQ==,iv:syCkbC38PhC8anzkwLwRFqYrDx1uwuLKfs8XZtgmFqM=,tag:LCiDWqbEzAXOYcRePvqV4Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:18:14Z"
    mac: ENC[AES256_GCM,data:nEWmPQa/i9UdcGBuk4AQctShOij5SB+aYCOGbL0sYV8Rzzm/0jaXMJZf9biSGf1vyRQyMhWhVNwLxAcp9dILlOzkXqyRXyT5INB3vT6hdXKjPKRczUlBYEbeVq1TqO4e0RA4+KVM3UDr43a1pM8tW3IHZqd7IMwfFB14ydHWYRA=,iv:SpxXikWaGJIjYGzZ1a2HgsrVIO8W4ag5zaEsYu0/jrs=,tag:+in2F1aH5sFL6KPuNzvgyA==,type:str]
    pgp:
        - created_at: "2026-09-29T14:18:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//XX3LiIbjBjkgju3z8q5uNd+0CqQ6cavqUxpuxpm/K63f
            fwQgQG9MdqkBF026sC+5pB9ybw749Fz4Gw1D9T9Wnto5n+UF59pBUpzQpuMxLMUw
            p/AwUA7iky6Q25AxgtMUAKzIsUqeMIsjkXHV2SOVvqLOcANRBhfp0JasHb6uObIk
            aB/FNsJGw2RhThfQHzvFXgJ+eIOJPzEwLpDrfHdOOBQIfoqJ8N11cUo0HQSMRniA
            kfY5rUYOzH5HRCIT4I8TP1upT2cmQF3457p9mHIB22SODuptxBj1QIzw2BLbmRyx
            S7z6GVLHsM2fJukey6FAw3DFTyZgnxL/J7Uu7YFZfmdST+9OaPrGmnEzwmSOus21
            6+YqLYiyHutopLvg1Uugz1EBhalaVuJ8xqQW1+VK4Jw++461nXJ4G9G0a0++Ru6J
            quIno28pSAheQGHJUNJT9ReTXcQl2vjHO7PUjOnLp8dX6806VcAocoolEGGCTJIp
            zkTOYKPA3V/nhCbKKmPFQDm1hjhDt90n32EgV57sFrrZUv/qJetovCyh6jLPPWbu
            W+nQQK6OPLgPz9o6h3kTdqU6bJuKYM8XITSo5rogzxFnkG+Pv3ufkld/zq/x0brb
            Z2XI+Zl4Raf2jW5dJZqBnnHFSNeHt2WgPJRCdxMNfcEXaddq5YS+vcUDelVQdN3U
            aAEJAhDufvhbk6vvd3jDIaRRUGjZOIm7fKWw4amiumVO7j4KROSwNfNm+wjtfUsk
            C/BmwqdzWez+zEZGgOrkrCWd6TH/hsgnSrqqqrYLCo/7o9ouDZdduvCk8mjofRSI
            ThurZmJ82xRw
            =qprw
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.3
