apiVersion: v1
kind: Secret
metadata:
    name: garage-backup
    namespace: garage-backup
type: Opaque
stringData:
    rpcSecret: ENC[AES256_GCM,data:JX9A4c+E1V+m1aZGVAyiFAJl+K92U/ZKgRMpWx0gOG6MTTLIdri/7KAuGAAMx+3H1Qlx0I/+7XKJMjL3w+UOJg==,iv:u8vGY/x0TWHdOmR+gpHR3xCwM1uFRg7xEP2KuVPHa+Y=,tag:druwoQ0/7cCU8dbSndaKGQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:38:28Z"
    mac: ENC[AES256_GCM,data:cCOrbJyTkbihmHICruc1Lry4JZ9udXyvGjfJl8X8B9ui6IIDCMU+BQyN/GNj7Es5Vht0X7+Gc6SOX9qOQWigs1d2+ZAqrmX+graGjt4Ly5Sm3INTTmOl+A3OC0YaZbF9UA87hyKieV/Gtt3cIIXndA2kMgpu84xAJhUuLgVlyPk=,iv:m2HgdfYH/f7t8+tOPojJwMiu2T6CZI3rE8kxB1xiUh4=,tag:ByAPZYRypfcpDkFj1JGVJA==,type:str]
    pgp:
        - created_at: "2026-09-29T14:38:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAtpFgKs1PHCZ0OkcADqXQ+XLi0vjh0eobKbtbxabwWRsW
            d5hO8wWWYwLNWnYF66n5WdTvX64k0bjV3fF8rtH19VLR4L1OishIwbMlmula82V5
            pNhDGShaYfmzxKkoVtKpQxkjI+cE2mUwRIGPhYG0x4UAo2AEk9/5VUqS9/X5VSiW
            R2+MbkTTjUMQemzHG9i5ezpHYvENbcMlFpAeI6qI1u65uYq5LzM1C7q5tuz1pqLI
            D13XDEpvX8Z5Lne4uJpYTWeYjVEnbfTQPrfhrUWq0YX8TpY4lm8NooQ+rZpR9N69
            ZSpTUGgORH4qVHLUMZT1uFNtnyaFjEW50uH0k6rSNXslwuZk3RR6E4p7C1fnqten
            XYOVhnyEFcMi81EdZJ2HZfpPZL51J+8CdEfqUo6VbPcWb+aEMlx8I5lRUbapqUhx
            PPHgtbPF+5ZdS2TIHgUGf0tQbejxFrZffZ66DUygEoetJ3kH69VaGcjIX0v+ktik
            /qWeA2JQY4QJnkNSO85UxeIpxMAQwlAgfUy0WsatQ1Yk5RvIFrWwpkd6gxtVMQVl
            NjE4ooyPe/UZUGXrVdSzUZxrorOrMnPpoBlKwnO9zJGeymOz+cesa2sGVr9pirbB
            jeekw6SL69td83/Ony1PmNJJ1SHzk6a2jBS4sOqVoxLErOlmfwWbFvM2mHatazbU
            aAEJAhDv7oaubES4EOmeMYRyUVa89Wc9uuI94JWUOPysPFxXkfo39PTZezIkCe5C
            DYWvxnSKEkskvJUxqpyR5JblXd7il3G3uWu8AHDF6k5u6a9xMDO465FiBt6TuT9S
            lBCxvw67CYoH
            =0bqS
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.3
