---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: envoy-gateway-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
  namespace: envoy-gateway-system
subsets:
  - addresses:
      - ip: 10.0.1.104
    ports:
      - port: 443
        protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: external
      namespace: envoy-gateway-system
      sectionName: external-https
  hostnames:
    - home.${BASE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home-assistant
          port: 443
---
apiVersion: cloudflare-operator.io/v1
kind: DNSRecord
metadata:
  name: home-${BASE_DOMAIN/./-}
  namespace: cloudflare-operator
spec:
  name: home.${BASE_DOMAIN}
  type: CNAME
  content: ${BASE_DOMAIN}
  proxied: true
  ttl: 1
