---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: home-assistant
  namespace: envoy-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: home.${BASE_DOMAIN}
        port: 443
  tls:
    wellKnownCACertificates: System
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: external
      namespace: envoy-gateway-system
      sectionName: external-https
  hostnames:
    - home.${BASE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: home-assistant
---
apiVersion: cloudflare-operator.io/v1
kind: DNSRecord
metadata:
  name: home-${BASE_DOMAIN/./-}
  namespace: cloudflare-operator
spec:
  name: home.${BASE_DOMAIN}
  type: CNAME
  content: ${BASE_DOMAIN}
  proxied: false
  ttl: 1
