---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: home-assistant
  namespace: envoy-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: tools.srv.${BASE_DOMAIN}
        port: 8123
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: external
      namespace: envoy-gateway-system
      sectionName: external-https
  hostnames:
    - home.${BASE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: home-assistant
