---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./script/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 5m
  values:
    deployment:
      replicaCount: 1
    garage:
      replicationFactor: "1"
    persistence:
      data:
        storageClass: backup
        size: 200Gi
      meta:
        storageClass: backup
        size: 1Gi
