---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway-crds
  namespace: flux-system
spec:
  url: oci://docker.io/envoyproxy/gateway-crds-helm
  interval: 5m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "v1.9.1"
