---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  url: oci://docker.io/envoyproxy/gateway-helm
  interval: 5m0s
  ref:
    tag: "1.6.3"
