---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  url: oci://ghcr.io/immich-app/immich-charts/immich
  interval: 5m0s
  ref:
    tag: "0.10.3"
