apiVersion: v1
kind: Secret
metadata:
    name: renovate
    namespace: renovate
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:Fi/cr0oZRl59EiYAXH2arcpr0T6ME0kW8Qz9G4W4fSaA75zuVf5AM9LFRI+l0Dp7SEmc7oleeroW3oV9VOqTnioCNmc2FvPfZK+CxPYPw00rDnUBLOgvIiqL8qgv,iv:6rMs7exWyBVKEBL0CL2CxOSo03+DqOMHtmunG8eizNk=,tag:6Lp03VrbHHvD1ZR5IJzFmw==,type:str]
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:vGJSEbdgRHPXDliSZlcs43cwHkdjrHxCElg1NOdOTQutQise2YmVoBmOhjSajhdeZVkl0ReQv7JfY0pGAcEhsqbjCsjXFW8+gpWg2FCixIkrF9+5hWz12WbZR1veC3ZVgNt9Fwc70kB1qhvIflafRglhob5lKMGwrGwKOfAiSxACAVj1mYCChvyoUk/+xxBBrnnN9JEYZ47DthdFScSuM/l0+PvEz8mAfZbNWsbhZBkBK/QJbaPqwlFssIZJ9LXoUIDaCGtRimeL8WeBl9LO/chdAfFXvybp4WyXkthW7+cfT3qINHK2j2wc6hapLNzmM/ZVB7qMlNvlzoM+XJOLOC8tHXMx0qbBmI+H2RByIWjKhhFauuJDlarOp26t750po5qc/R/OVYWzEg5fhmpvH2v40mDRfwAtdLzogiXIAX3/OZJlpLsk3wKZtXLAPfXGWuZfoexbiXKvBrOXKM0ouA/Qj5pusbcY2f0igl3taBx9A8VNkabL6gdEhxCN2swpIVOTOQORYn5MNeDuhQgMQNoP361WjeiFsKckz2atFf1JVBS2wPm5VTk9HmDpTP+uNiW2/MVf42gn+9oW/Id1Ry0amF3/y05x9Xtz4oOjtG/gQDBDL50Zc76dY24I4Yy73rFe628kRHDgKktk4UjLvzSLx309oZpVo2BLeCTVCggURls40k21yeW3qkR8hvx9C1hH7z0zyVQn9crUMbyFOUHjO0Js4LOUGc02mZAB2VCeXqz/DQoclIryBNu6H/t1unj5d4HshrA1dQgej5hmCrzTQPbn/Q8EB7W2+GHfvK7PWqGjmuQWhvN4wCZBpodvQU2U7E+cyNj46toAOpL9B9bFxwAOZ9EFiTCiTjfQ09dqXw+c5PJaiP8GupjhMlEnEf1XnfjCxUS6G8V8Xngl6rJzbPL2rBssuJwUk2Mnnyp122spZrnhGyiB9jTHGimdQjnBBy14odTN1od8msBC8Q==,iv:e6HA7hCcwzUULUNLhVarzAgT+r51lz1d2FA+2WhPGaE=,tag:AUiXntm/oGR5/Ho+xcn1mQ==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:DMXGl2ceu5FjQ/w8KcDl3Iw704T61wA+g+Y=,iv:6zzoLJou3TrnCLgHg3y18BuOeBxgFMysiOpsvnSzveY=,tag:6lJuv+/aLEhJNi9NIDSrDg==,type:str]
sops:
    lastmodified: "2026-05-01T00:04:26Z"
    mac: ENC[AES256_GCM,data:4g2j5EdP1aOeTnU5AgohsdupLSvMHg8ZBYOvyh24LU4/QjmPKVFgqIIaxYNUvAX+ZB6DpNJdhLJKIp58VjyQlYq4N6ytMUgoClTrtEsAmZGGCdYf5uMtXZ3qux3Hd01Arozi7bJecSOXHD8tFH/v4CED1IFkJf9H/cQoUQj5YZo=,iv:A3rKMbFeJliDrS8wrJgWJF+JO3L9ZVuBx9Ifjj2miAU=,tag:2zK0lKWnHDRV6hULik8xow==,type:str]
    pgp:
        - created_at: "2026-05-01T00:04:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//VwQnzzwwB2KmJKk8s85lV8Q/uinxKEL1udLFETELccVS
            +9CfAcVSVJSK5iZEklG6byVD97XrMFrJtHh8JP/o3SCjDpj3+Sk/IQnhB3xEojJ7
            fSRPQrnNMAui60Fu2k0vR9gRXWR9mf2U3d4IX7eQW9fMnt1j3HB2gzpbxPZsX3vK
            +I2WY0bgeuE6IYYwGM0fw8s/LpUVe0u9lTfXjDfmEC/sbDjH6H72ZNp57xIO1Vfk
            wXjVUnlKxTf0qIg9Xc/oSWyHZ++Cam66hNc3TrND0FuH3RmtYACCtqVVfZI4ojmD
            TVeuYlvzFYA4Sf8QP2v9k5UNAzKDsiwLq/fuCMiUJGK9So4ri58nML4V8i1QS7Co
            LVZ+QEMy+KsQFE+wFxmwe2pClSa/aTqyX3A1NqzIaFg61InhFsoNM/Szjo/K2kb9
            DOiHLGXDToAbxQWkdsjtaMOL9QaFOxQEZlwYRIMhwelp4sfuzSUzqmUVDV7cBmfE
            5cQHcvDMtldL89e8fCzGRzA+CcC9cNoI9VzJ5HKJ466R8wEVqTEuthsdjx5aaC+V
            v6UaoKWry7PwUIgnfQIBdqKjccrYblJwQQ7eWCNlSeJ4pyzr6APLOmjgHzF2zV0J
            4k7N6iBuIXb6YjNqw+thurSwZKUmDr0Z/12GJ4e7SmsVcRKw6NrQ+kf9QYRARVbU
            aAEJAhB/ZAFdTqgv0otemQIRSS6xdz7CV+wPYJv3/2kFbwVZRe8uA9y7ZMp+z0se
            Ad84xV3I7Q08Ikmifv5UYkZXePtd2P29OWeAdWvUV53VyvKF7t1UR+QzdzvbdTKW
            4wezo4C+R2vV
            =KXzi
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-ssh
    namespace: renovate
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:G25nQQ3c0xxF4nrc5m9KQpVZbWhuRHBcdozNkYpVtrpKpXlFNlD2dhIrLU+h1WYQMvCfuUUVzeIOq8v/dXnFxYqs3MnYblNioyaclUpfmdT5cdgGFGBR+hWOq6IhUe4SQitKfI0UlIpmLS59g+oixTlBicN9kFvWi60WuMc=,iv:YFpXybtNQlonpdepeYNeXE/FC+Dgok8BY6chXjR03kE=,tag:PK56w2wxt2A6dKi/vNKZvg==,type:str]
    id_ed25519: ENC[AES256_GCM,data:Tu+CY+LVvqKoUwFXjw7msRKufRx6++jTYL+KBhFhUFtL4j2+bKJLeIjjEerej5gcGZBvctp4d2eONitNDXCmS7Q+F2h28JXMNF4JeDejlXVqRVa2cqUhPxmufx+kdBS6/Qh8+weNZgCfyOdIPf40lgPMHbMxIH9pi+Pm7j1Tyis7t3LwwfIWQrrwzuT/y88MpOT7FQ69qr6Gz6jMIYISk2qbvY4iIoXI/C5jPslM/lkb3EYwszbsW8tnaIkr82zUw/tZ4ZrlrkR7Oc5yf+7tZGDUyumueNyGgnBuWeK3WB/DR3tSB/9J3cxOs/f9ctOZIVmZoQA+9juL1pFlnowLMOphzaKOfzAtjjdNSVbbphH/olW0wqTjwhQWDi0DHQNAQP8aMhfrlf8JNLuuSeWdB9zvA3p1SJUJCCl40fvxnhKNtDUuieMQAUwTbkhshk3jAeHBBFjAdVxkGLCKVMRCViOEpITOqp4IYE5yaAWA2i0AByuGvg1oQWm0SbyqdNWieh8MYhjg+PlHLge2bN9gNbyiCyMN/rckj0S0,iv:cd61zzk2O9NHXmRJGkOyzUfzHcPPlnYC5Bk0aBmWzgk=,tag:AKXmHgd2F9Dsukl1KslyJA==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:J/Vcy22jp4YCfPvYtB6Z0l56nHN4oZ7x6N6funMOKr3Fukce+zxCytYzIIo1JECu5Ga2aVOBBgan6gPtBiLHAUzMgHmFipLb45IjrE6XdfPUKwmWkjfBtUNTIGou6TqX,iv:pYUskI1ChQjn1WUk9iPA+X7OX+XLCWjexSCjY6oT1jI=,tag:Aohc0ucWV4yPFX1zRY+YVA==,type:str]
sops:
    lastmodified: "2026-05-01T00:04:26Z"
    mac: ENC[AES256_GCM,data:4g2j5EdP1aOeTnU5AgohsdupLSvMHg8ZBYOvyh24LU4/QjmPKVFgqIIaxYNUvAX+ZB6DpNJdhLJKIp58VjyQlYq4N6ytMUgoClTrtEsAmZGGCdYf5uMtXZ3qux3Hd01Arozi7bJecSOXHD8tFH/v4CED1IFkJf9H/cQoUQj5YZo=,iv:A3rKMbFeJliDrS8wrJgWJF+JO3L9ZVuBx9Ifjj2miAU=,tag:2zK0lKWnHDRV6hULik8xow==,type:str]
    pgp:
        - created_at: "2026-05-01T00:04:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//VwQnzzwwB2KmJKk8s85lV8Q/uinxKEL1udLFETELccVS
            +9CfAcVSVJSK5iZEklG6byVD97XrMFrJtHh8JP/o3SCjDpj3+Sk/IQnhB3xEojJ7
            fSRPQrnNMAui60Fu2k0vR9gRXWR9mf2U3d4IX7eQW9fMnt1j3HB2gzpbxPZsX3vK
            +I2WY0bgeuE6IYYwGM0fw8s/LpUVe0u9lTfXjDfmEC/sbDjH6H72ZNp57xIO1Vfk
            wXjVUnlKxTf0qIg9Xc/oSWyHZ++Cam66hNc3TrND0FuH3RmtYACCtqVVfZI4ojmD
            TVeuYlvzFYA4Sf8QP2v9k5UNAzKDsiwLq/fuCMiUJGK9So4ri58nML4V8i1QS7Co
            LVZ+QEMy+KsQFE+wFxmwe2pClSa/aTqyX3A1NqzIaFg61InhFsoNM/Szjo/K2kb9
            DOiHLGXDToAbxQWkdsjtaMOL9QaFOxQEZlwYRIMhwelp4sfuzSUzqmUVDV7cBmfE
            5cQHcvDMtldL89e8fCzGRzA+CcC9cNoI9VzJ5HKJ466R8wEVqTEuthsdjx5aaC+V
            v6UaoKWry7PwUIgnfQIBdqKjccrYblJwQQ7eWCNlSeJ4pyzr6APLOmjgHzF2zV0J
            4k7N6iBuIXb6YjNqw+thurSwZKUmDr0Z/12GJ4e7SmsVcRKw6NrQ+kf9QYRARVbU
            aAEJAhB/ZAFdTqgv0otemQIRSS6xdz7CV+wPYJv3/2kFbwVZRe8uA9y7ZMp+z0se
            Ad84xV3I7Q08Ikmifv5UYkZXePtd2P29OWeAdWvUV53VyvKF7t1UR+QzdzvbdTKW
            4wezo4C+R2vV
            =KXzi
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
