apiVersion: v1
kind: Secret
metadata:
    name: renovate
    namespace: renovate
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:E6JO0rKmSkZtkAfrNWeWpRUL1INF1cCJEvqbdhhUyvyShWunUdHsmJZVL1xVD6xmyC6ok/6/mrJgdeBmxR3lJa9NCowB+levZJVa+OyDLUZLzN6BkZPqw2M/amz+,iv:4mn1y1JIl51e29oS+/bBa5BXqyKaSD0nQKR+IkzDYDw=,tag:MIq5uGcd8p/ovxWONcaQXA==,type:str]
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:TqFt1Vc5YWh1U8zZa0zt6hHisNhRXZkn9p4KVx1ng8ydNWjoNEU5k9uIXVAqUwNMn0gYAbMquFkn5E+QwrTFVsTXGl4cwra4c3VTfH9dsLYex2HH+kT7YMG5mvi8GiNmeQ6/+yI4uvKe71W9lECnc5nxZz4pxHiW7qfvenNIgYaQ0ybauUZ5wSJzj8s1Kr4iNlnXnlnYGYoRigFZXfjyT72mP5CQVwPVlCpVBcSmVpsyER2h+ulKU2j2oOhj/5qK1J3eojmCai5//1B384CQdH0s1WIxTGUgPAhs8QCdaon/TJMTijq+guShpcMhZG3bsbuCYv+lZ47xlkItC91uz76eKN6HlXFV5ILYdNIclqGKKuoOgZeg8GNdfOBmgHQM2ACrdvy1bnToMuJL1WaCKmnu2BwT/Io/WSexVNXjnnAxVEuhmswKiEsvLU/1UwMMKMPCz6l/KjKDbwix57oALCRJ7B9ujjXJmSdyiwyfptGQoOo3bgG33p8qfdY5IFoqAOc8u37ddEjnvaheazQXwVMRBRe4evY6toJICE1EYLD1lTi1IN0wwGtEqgy/zfp9VrXKbD1/pZTvVVx1969+dFOQKxfPdQAaEORbPaGE8vsXyILBDD3WZMjpjH55q6aTkmeNSWwVjrOGtedWA2w/3fbsXKonS1mrEekYGWsDpLGTtWpJ68oQN9DZqw6R85Y0CVbMzhrlJGCDwiRln7hBfoDiUcteWd6O4GXL0fPzjbOPmfCqOnLAgg+fj3p9LhvTFa7pCtnkT7s08Fd8f75lbPROHG0VbY5GSO01MPuJhlcVxYrTbbh+iA4nh+CPJSMod7oqvw+IbILTclfOW4XN5vnceAkrQDVKf6L6cn9xNGhayTlK/Q/CRk8ANBMXMLzcx9aT1h0xKzaovpx1gEZtt0R8l+xr3coQtqi8Y7VaWzrwF1HCbklRqiX+PbaXp8Zsnp6VYakYoCDZ0pGGpg/0Cw==,iv:HMl0kte1uBcMhlN3ZvxsWAdfPlMA8NQAR1nJDb2lu0I=,tag:3qDTZRqVHSW/sELWk/mtLg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:nq/4soBSDgKSwthUL9Ka97dO2LWLuKmeb3CH2N/fJxxQxQk9w2gLlyCRPSXylhC8Vy0a,iv:Bp+lx2OBHX88KnATXprIy9O1o7VJ5EAQyqrjdbyNNyY=,tag:Crdt9TOCZXVLiQ0vGBwHhQ==,type:str]
sops:
    lastmodified: "2026-05-01T00:07:12Z"
    mac: ENC[AES256_GCM,data:Y42geitXtgVbmxNaQXtePD8Tz2Sya6+FkdtmRdgcDg90Qar11Ay7j5zqG7PnNI6AXxr8a0NIE0EBsUNcS5y2dGKHymEEV6GczKc9475wkoHZbQaLUfyUl4sDGmybmdv7L5XnKJMwJoeDAGnNttX6TTsVWgL9ovD1lVoBg5WjgPg=,iv:Gv+hb7msmA08hAVi1FTEP3EfmvzQto9XN/gl39VwgJs=,tag:KEnYSCa5CSSOVwoiuPQVSw==,type:str]
    pgp:
        - created_at: "2026-05-01T00:07:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqtbM6A6GyIj1rzld+vOcPfBuCZDxsGPz9Uzh8c5Q6II4
            +DS2VmozL2/mmlbLizqyA4VPklMjqENV+1M7famY6lbHAHjr35eLuVwQnd9O/BCY
            Upoz9U88t5D9ge7EKiA4DIPHP4wfY8MBFRajoPRVatdgr7n0c3/dnUNWWStg7u4X
            ktlSvR4lhPkJv/oKkvChuVoct+kME9SsfGPd6R4WMhUT0F5pGIoVKfkttAp0yEJc
            FUCulCjAMUH6Z+Wn7d9cWLlF0ZYRluXwzNwIBdkqR+JmLZ+4fDCg10NCUIJYvJ/K
            HirPItiKhFciwS6XxcrSXp+KGGqlaKXu+iKyP6isrgFPmaKCY7taTWIiHxvpvd+8
            3rasZS+J6BjC8mo4EK2AedxS1IFu3LGt41QirV5NKRHD3Cs7Gr2HhwuN5ZSm4zKe
            6wLhbm6R7BTZcfXWCAmVgCQAlWGfvraoIDxyyvJBO1x34deIWVyeQyZVnX7C5vcL
            yDMoDzPLT2sR9HQskT9nz3WbqU+bSF58+KD5IuQMVVJ5tc5rSkV/IJyMzXz4vbmS
            8cTgjFFPwO0dwDpQrroYi6MSaAa0tMmGmaS7xq1fgJCaRwDXDaxzYsMGA0ksRkYh
            CM6JEdG+F1pQwEMyHOA5cwdgZHD+XzbaJUp2IgT6R2djM6aCVomIThcsCZxWe03U
            aAEJAhBR1Ik5/Bo5nh/yh7TmvUqCjilhwxU7O1Bapyym0nfGuym9LJHcqsj1Vbm/
            DYjBeDTar4+KWCRCcZ5QCLSkDZI3WpcGbLuP0v1dX/UhKT45K83XeTJtVGkpyqyu
            EMCtmRRdAnqt
            =Sd26
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-ssh
    namespace: renovate
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:KKgCAhGAmWThiXee6WaA2EGW6YN8T6HiL4Knlk4NGNy8Y6iZDkkkQFOhdb9E/Z+l+LqRTaTc6MgnVJM1eYTiM9UxqOW4c0T4p1ZgCW1FBENw7ztWk29hxJlm0eDsW6N5AL+YiiQCYo7B9XJz4R3s2/rDTsczlHVIx4jD1yM=,iv:NGJd+BWb/NhjhlVNf6LXdaDuLsh8svJ+AIRVnrj75z0=,tag:+z0Dmg18Ud7YiVUDK/SEog==,type:str]
    id_ed25519: ENC[AES256_GCM,data:FDH70/ALBfr/S925iL1vazy0EcxDrCfq3Xc7AfhzqwQ/TehdApZqgjRb9Ed9bHG4Y1Z8zb8ZzupIb0Bsbu8sguE0SKh6Fobn7r+pByhOkYKTtnHrgszDsKqLXhmfc87MRqx+W646xycEsJAGXtwaGsXuaEG0V2GQWMnAoO32GpTAN3a4XJbT0QAYmY+dkVm3EYT/oMbR1IbwYxhI7AWiAzxM7iY9xZ+01+GtT+Atr8EI5Ww/qq8PCSWfuoZTAPoSULVBjQC8mHbe5uibApl2Snh3izgDA99E7nLj6FGq8BvDQAMS9hyZtxIZHfJnv69Wnh/TRp29lf1s81dB5YX49AW8lW707G9DgDvLujyO/Xavo3w4gaiNavCpbZ2gaVefgSziOSCpMzp8IBGX2gll9XYoqt3J3dHrCC1sjSzKWslUzQ9EJu2a/ShhWFLz+4CUMWMiGB94hxsnu36nujKNtUtuLXJBJ7vm23UwdqlycAgyHFo1UuVJ9wYuswVg+XIJnbTHCq2M45iX86qt2c1fwv1ooGgyMychflAz,iv:SE8IKfuceTMoRyyPw8/SDGC00F13CBvLvoMwEUYSM5k=,tag:biwMf9cTcSo29d876DHQUw==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:I5+n5gny5bcAvc/+ZlKbazsQVg04Fo04DfYuUBFqP44qfBEpEZcyFezcCO9b9GiONacvm0T22VfNAUgmWu8qRiyuuQ9EqIJcU6aTaMIcgYiFHPfVXuW9m0eDMKEWq7Fq,iv:95oUiEH0gX7diV35a82/24VBFbCrseRM86HiS5/SaHM=,tag:wsDLGqPmdJrx09HLKPfaIg==,type:str]
sops:
    lastmodified: "2026-05-01T00:07:12Z"
    mac: ENC[AES256_GCM,data:Y42geitXtgVbmxNaQXtePD8Tz2Sya6+FkdtmRdgcDg90Qar11Ay7j5zqG7PnNI6AXxr8a0NIE0EBsUNcS5y2dGKHymEEV6GczKc9475wkoHZbQaLUfyUl4sDGmybmdv7L5XnKJMwJoeDAGnNttX6TTsVWgL9ovD1lVoBg5WjgPg=,iv:Gv+hb7msmA08hAVi1FTEP3EfmvzQto9XN/gl39VwgJs=,tag:KEnYSCa5CSSOVwoiuPQVSw==,type:str]
    pgp:
        - created_at: "2026-05-01T00:07:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqtbM6A6GyIj1rzld+vOcPfBuCZDxsGPz9Uzh8c5Q6II4
            +DS2VmozL2/mmlbLizqyA4VPklMjqENV+1M7famY6lbHAHjr35eLuVwQnd9O/BCY
            Upoz9U88t5D9ge7EKiA4DIPHP4wfY8MBFRajoPRVatdgr7n0c3/dnUNWWStg7u4X
            ktlSvR4lhPkJv/oKkvChuVoct+kME9SsfGPd6R4WMhUT0F5pGIoVKfkttAp0yEJc
            FUCulCjAMUH6Z+Wn7d9cWLlF0ZYRluXwzNwIBdkqR+JmLZ+4fDCg10NCUIJYvJ/K
            HirPItiKhFciwS6XxcrSXp+KGGqlaKXu+iKyP6isrgFPmaKCY7taTWIiHxvpvd+8
            3rasZS+J6BjC8mo4EK2AedxS1IFu3LGt41QirV5NKRHD3Cs7Gr2HhwuN5ZSm4zKe
            6wLhbm6R7BTZcfXWCAmVgCQAlWGfvraoIDxyyvJBO1x34deIWVyeQyZVnX7C5vcL
            yDMoDzPLT2sR9HQskT9nz3WbqU+bSF58+KD5IuQMVVJ5tc5rSkV/IJyMzXz4vbmS
            8cTgjFFPwO0dwDpQrroYi6MSaAa0tMmGmaS7xq1fgJCaRwDXDaxzYsMGA0ksRkYh
            CM6JEdG+F1pQwEMyHOA5cwdgZHD+XzbaJUp2IgT6R2djM6aCVomIThcsCZxWe03U
            aAEJAhBR1Ik5/Bo5nh/yh7TmvUqCjilhwxU7O1Bapyym0nfGuym9LJHcqsj1Vbm/
            DYjBeDTar4+KWCRCcZ5QCLSkDZI3WpcGbLuP0v1dX/UhKT45K83XeTJtVGkpyqyu
            EMCtmRRdAnqt
            =Sd26
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
