apiVersion: v1
kind: Secret
metadata:
    name: renovate
    namespace: renovate
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:CG9trkdyYV86UBuixtEEq4oGpvkRztx51Fi6gjX7xZdUInsEeiEwc8YskmPqBzo505AXBfx8d3o9AbcPYsVXgs5htwNair21nXaqUD5bUwiYLsahNLmfZEizs/J0,iv:eiYVYs6JlxDqjJxJCMtM+77UA20Uz6eMkKW5zRrGkr8=,tag:/3xOdyAnxgg4S8+WQ5dSBA==,type:str]
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:MoDHjxSmbWQvzOeqWnlsQqLjx99LzhfOrxyYBSBiKRL8K/k9rNMw50+uchJn6juxaQKX+k85qIFgIyB+2ysYKYTfpiUxwLlToFXrPMdHbdCMD4P86YJ1M+ewfhhHWXnPFCvBwUCcLMKHjJHGL2SfoCHrX7RCTJYf536CH2l21igqAl5tFlDgpgmH0dC6XqSOGkwI+fP93MlaoM3MA5kuOiFAa07Ip2vZuORaNA+eCstBmqr3SybB1+Wld5zW4kFZpGpLt7hP6CjjD2ojYQzEUHmSYY6F/aX2h5kEjZh97i8yd2RLr8NgvPjtO1GdWHge6V5ST4sUsKOo4tDB0Sqih2pB/N37pg5/oPqxovyAzzyLeoR2WWHjQmXV3YqjPZ/Gm57/pp3UwDYanuUkV1r5IDshse2hfUG43D/VqIIdf4ByHZxGd1P0TDYu905LjFVdi2Crqan2jc9su08TpNyEsqGLiHV31zTuIAM1GBTxb0x5zbs6q0sJxfGVjfvey8hOwgFim75BZNKfl2r1kTYGbMHSFcEYSbhRR2Ti+l/HIISKlga90VsEgENOQo1I1eSKZuFHjEOlY0U7d33amvEMfXtSi2dvZw5txg0Coqsm3Y6P6Qjc8oNwfpKc5YjCunuG9GGGo+d6x/yp9cXwbi3V61+eshUBliLUNdNtIzKs+cAUpcdARoeGJFa7fonVAlT/3blgVo9vUu681VnrV3A+HrjOiYSKKnngaKabZWNPFaXmil4NlTfHGUF0hkCdkdLWCb2U0uzwyTEnh0BbeyxOm6vJgGufEayzKCwMbKzObEv867PY6G5mJCJ3bG8EPYbPh5Zh49bYtS5l7r4ihJVPsAnqiJduzVnmNsk429tvofcgV7fugw==,iv:C2NOwmTtlfstgpUyxHEOg5+7AEDsPO3RCmXq8Y/xvx0=,tag:B8PWn7eickdVzVK155ndpA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:SB4ZBw/wOBTwoO50g6qQyOZ5y+cIB3hnIxk=,iv:61TQgiR2lqSJ9+r+Yz6gZRTCcGz4HEopScFZMcOhW60=,tag:lJ7KoYHVTS8f1AhyJ3FYWA==,type:str]
sops:
    lastmodified: "2026-03-31T17:36:07Z"
    mac: ENC[AES256_GCM,data:Bd6jMwVe9zOvPka88H/O4OuqCWYEM1bZ+iXO+UszhvRBHsOHQqaucafRHtEEmgwg/fOz3wqawaBKW+6y99FZv4bfkDAuNybzUWsLf7gpxiRk7hkCoTE9TdW5tUZVD93Oxviqiyq2TgnHgRV4/aF2o3WwFY01WbhHHeaY84nSF+M=,iv:sgxvGplR/g3ydYHBqxgrZ0ZIPsZqa4d5ok/fpB20dbw=,tag:gEDIRTphhfzMNIFCn5o3JQ==,type:str]
    pgp:
        - created_at: "2026-03-31T17:36:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAltDVXujnxuhFLr5+evJbFcvBOm2JjvK8ZKykW51IOBAW
            6UJPAdOllQsd2cB+8i92hj0sir3DdBdFBvSFD2vEveBpxZJp0nPI2FbnieDdW8U2
            hlXlcTK3GykYkLCJrBHgMdNNuhjJ1gM1CdP6AruVEEoo5TGSC3aTJWb/O79jKSHV
            lM1S23hELgVJR/Sf8R74eBqzxVePpqCANpHtcCg4AsEpEyOgQgBM9Gim6UE0mdYT
            U9i0lOnoBxtABrpDuzaTH7o7A/9H42LgOKlB5u9EeieLSC/bvHlW7QZrOWHeJ+K/
            Xyqi0M6F8vNXKKgMgahpVxxlIRTy4Z0Yi9yX1/9fjbmKSvrJWo4oKXh3qQLymOMJ
            qztNF+lIMxVZICq8pehQ7etbNYNn8Ktw5hiXHiSR/vybfsiknOWMSYoEl1aAD/Ze
            gcVQxYx3ccr78pIvDbojbjy/vUV5z2ZvXlj2woLATew3u1t13f2xzFv0Zqa9HSQ0
            WdOAhDiEMFjEWtBZ/IWHBB1vPAMAnmxiyCdPcvfvTfhPNYVm2CbBUVIc5vU6FRZM
            WPLz+Uhj3fME6FdPSic2T+HJzwh7DBCj2ceN63owTmqZJPPslgP76QZKS6jHtK52
            Rr0MTp3fG1myb04z+YlGtngVT+0Q5QL44eH448VpXEFZpw5o7cqb0vJ4uMyAwQrU
            aAEJAhBpETUlQxWIzxRgz19cHfZGtT7wHeuZkFS+opQ8IeXv/oVbRdGjWSDeem1q
            4qu9EwOKNRiDil9AenEnicubwXwmh+tRdmSwBeWl2CWH32li6Dop6tC72FEEqz7K
            tQi+N86uM0en
            =3ajt
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-ssh
    namespace: renovate
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:50DYBEYvb2FcNrrM/xmSt0tD/jgifs4oEyUwTTKxHd9G1dMIbcr88jb5dKKbA0waqhkSOjiiGeKv9OSpi0F7485BVg0DnWCulTSrduaGb4KUdgReo73XsQJgJGZeOnTkqZHyeAP9DHEv7gpsQmX86DmgobSx+Tt0MY+xhaI=,iv:zKvmFVa5dDp6GqrdHfjbo4mImxpLI/WGzNOvUqJRu38=,tag:9+NcSD71ajifNJlxirqTww==,type:str]
    id_ed25519: ENC[AES256_GCM,data:KFK/BvLNGPHAScLMMVGH2XPD3Wun9OyFUaC8egsO3BILNmUelbSLGLQKW5gcZCon4noTla+8MogmuKyqC0t0B5R8a6xI+G3+4blyrRwQkrc8fYUhg69yKc7e0HOQQxPVnxm8aRaLBaAys0ffmhw0J1tUvl64wKPNwb3Rr2h+0BRWP0qhv9rONCg0ggZzTm2Fn4cZbEZfz0vZnMBaEtbUCmPpuy8jrkjoU+yGlWApFHc2vv8/RZU+4mdz3NuJXAtcSZBSdFJFaOkCTufuukeqCKWmQ6L8P9vw2YYDsLyMtl8vkXY70QAxBpqHVr03kNHKPqnVEhe2k0BK4BhoTjOV7V+v70/4X8DcnBtEVo5fX8DLzXPW17FX4eytWO1qBnP83MjRXUfhquEIK6NUMD69tAtV5/3Icykk8jq2v1ZZaWKoVvvI2LpA9OT0aT5JWSRDFOQ0GF3b/GBSmxOGhKy1kGCZxa/Ocv6H1Y3X8NQ/MsSNMpp/zNTS08S+sdnzAjwmNVXlGxqkD3p6n0vIQWWoLX0ZEBbVQ45hUJX4,iv:SBQWZ2iceWWdZF1iObZiLMJn3CGNAGBRNPHhn5pnkCk=,tag:qWQxdx8eQP4dVAeAR5YkVQ==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:dKH4p/kHVKkiyF63bfgh5ku2zYwA97ubUl/DZ7OCRgxe91njjgD1YyYcygYinKRvsozXNhhcSp41p8whLSc+Aj1JOg8I02RbBxi2cagFsp0w7CiNzcEyHGyBNt+uKP4u,iv:YgTqqRCwBYe+30jNasIBROw83FXwS+uotgyFQA7ksgw=,tag:YxMm+cUl7QlPk2sujgtL7g==,type:str]
sops:
    lastmodified: "2026-03-31T17:36:07Z"
    mac: ENC[AES256_GCM,data:Bd6jMwVe9zOvPka88H/O4OuqCWYEM1bZ+iXO+UszhvRBHsOHQqaucafRHtEEmgwg/fOz3wqawaBKW+6y99FZv4bfkDAuNybzUWsLf7gpxiRk7hkCoTE9TdW5tUZVD93Oxviqiyq2TgnHgRV4/aF2o3WwFY01WbhHHeaY84nSF+M=,iv:sgxvGplR/g3ydYHBqxgrZ0ZIPsZqa4d5ok/fpB20dbw=,tag:gEDIRTphhfzMNIFCn5o3JQ==,type:str]
    pgp:
        - created_at: "2026-03-31T17:36:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAltDVXujnxuhFLr5+evJbFcvBOm2JjvK8ZKykW51IOBAW
            6UJPAdOllQsd2cB+8i92hj0sir3DdBdFBvSFD2vEveBpxZJp0nPI2FbnieDdW8U2
            hlXlcTK3GykYkLCJrBHgMdNNuhjJ1gM1CdP6AruVEEoo5TGSC3aTJWb/O79jKSHV
            lM1S23hELgVJR/Sf8R74eBqzxVePpqCANpHtcCg4AsEpEyOgQgBM9Gim6UE0mdYT
            U9i0lOnoBxtABrpDuzaTH7o7A/9H42LgOKlB5u9EeieLSC/bvHlW7QZrOWHeJ+K/
            Xyqi0M6F8vNXKKgMgahpVxxlIRTy4Z0Yi9yX1/9fjbmKSvrJWo4oKXh3qQLymOMJ
            qztNF+lIMxVZICq8pehQ7etbNYNn8Ktw5hiXHiSR/vybfsiknOWMSYoEl1aAD/Ze
            gcVQxYx3ccr78pIvDbojbjy/vUV5z2ZvXlj2woLATew3u1t13f2xzFv0Zqa9HSQ0
            WdOAhDiEMFjEWtBZ/IWHBB1vPAMAnmxiyCdPcvfvTfhPNYVm2CbBUVIc5vU6FRZM
            WPLz+Uhj3fME6FdPSic2T+HJzwh7DBCj2ceN63owTmqZJPPslgP76QZKS6jHtK52
            Rr0MTp3fG1myb04z+YlGtngVT+0Q5QL44eH448VpXEFZpw5o7cqb0vJ4uMyAwQrU
            aAEJAhBpETUlQxWIzxRgz19cHfZGtT7wHeuZkFS+opQ8IeXv/oVbRdGjWSDeem1q
            4qu9EwOKNRiDil9AenEnicubwXwmh+tRdmSwBeWl2CWH32li6Dop6tC72FEEqz7K
            tQi+N86uM0en
            =3ajt
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
