apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:xIiDtatPHNFempCQGlxKXHMzWZQw9Vak3JQLODOWrtgME+5pjTBO4II=,iv:nOYcYRNYOYTmOrnlIijJu83hKvGiom9o4HvHgs4xjX8=,tag:ec2W9WjQVZ0D3FwrTbag/w==,type:str]
sops:
    lastmodified: "2026-02-24T20:31:10Z"
    mac: ENC[AES256_GCM,data:vXmKwGKM4/7q7YPt7JSZxWrHk3jKf3LaQRWPdu7o9g4QqLhmBrhwVld7BKI4qYHzKtOqKJC2hcmBs7ofBIrWk99GVmBtEJenmxEVluxwJo2NxFxVVYl3XY3BVEvlmgMnirEyXS6buMS4Gt6DG4eq/dwMx/zjCltWcryGvGfp8XM=,iv:dKXatRzpLhtkq+SV/Sd4cj3rdF60fko+CBEAv9ncJB8=,tag:Bbeeimc80k415CB7GjRFHg==,type:str]
    pgp:
        - created_at: "2026-02-24T20:31:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ/+MCNjnYRFZRCTEtNlrxLOfEtwMts+bT7sR6va2z1WE+FH
            VEHaGVj0EeD3e+mNcVZ26IKbiiZz9n3WdXfi9T+oBf1l4gt+tXINjFpn86Gji8+D
            Z5QdL7QiA8XnuKPE3ELGJ+FgWHkzzrHGx7rYQmrqsYIU4T04SKoVudZemwt0lNBU
            sNGjdyYImdQCYxRzGwOQ+QFwqIvvjEDbtVtQneRrT6rfbaQvRd7mwjYpqLCnvZGM
            eD4gVy3P+Kw3eqjMneD+/caeM+wX5bZD5SffD+I+Er8Qh0pXQzC8HXcj3jFOpF55
            NErXVXKwDlibHppbJU5JzjJAgK91cjxxod0VxOLuqPcLp3bPh5Ee8+dYwtR7ZmV9
            qmedWtaKpu7bwLlKU0pRWbR22ufBoLlg123zedzi9jBFuMXMavPtJhI3/PsxKRK1
            cH6DBwq3/ryNVk+HWDK0ggWIu1hlHWKm1HbSZvBNoL3RfPGBdluCBDThOs9GrB17
            S15/bxFYyTVdy/qMyyhL969HLzVDfxarVCgyGexHUk3lgdollrSYktRsPYsklSdE
            rODQhEwBOX+7fB+LOXUKUevBxrRsXY+RBbRSqMG3+3AbdCduW+IoOIHGdns6+rY4
            N2I4PNw7IK8SJT/ju/87fuNnIK8fMaeFT7ehqCuYLDG5+mIA5zWuVBmamZnNEMHU
            aAEJAhCJJQiD9T238NK7kCIoCCM0p9xaoG05ZgQl2YiBgMIypU0qRtOKLNGs+Mny
            LmuakzMCn4LBXxEf80wpETrp2kAIszX294IHi9akTwJx4+cC3j7QAAf0CdOHl4PZ
            X1rYV/mdgYL2
            =eP4P
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Pn7MqLixie/GEGBkt+jkH654VQWR4B3JfrF7cm2bFp4=,iv:+qsM6ojYy0p1DGycxKUrZCX4dOSCDDMC+JLd5mJApkQ=,tag:NHdUYiu6TLvAIzpJ2BhOGA==,type:str]
sops:
    lastmodified: "2026-02-24T20:31:10Z"
    mac: ENC[AES256_GCM,data:vXmKwGKM4/7q7YPt7JSZxWrHk3jKf3LaQRWPdu7o9g4QqLhmBrhwVld7BKI4qYHzKtOqKJC2hcmBs7ofBIrWk99GVmBtEJenmxEVluxwJo2NxFxVVYl3XY3BVEvlmgMnirEyXS6buMS4Gt6DG4eq/dwMx/zjCltWcryGvGfp8XM=,iv:dKXatRzpLhtkq+SV/Sd4cj3rdF60fko+CBEAv9ncJB8=,tag:Bbeeimc80k415CB7GjRFHg==,type:str]
    pgp:
        - created_at: "2026-02-24T20:31:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ/+MCNjnYRFZRCTEtNlrxLOfEtwMts+bT7sR6va2z1WE+FH
            VEHaGVj0EeD3e+mNcVZ26IKbiiZz9n3WdXfi9T+oBf1l4gt+tXINjFpn86Gji8+D
            Z5QdL7QiA8XnuKPE3ELGJ+FgWHkzzrHGx7rYQmrqsYIU4T04SKoVudZemwt0lNBU
            sNGjdyYImdQCYxRzGwOQ+QFwqIvvjEDbtVtQneRrT6rfbaQvRd7mwjYpqLCnvZGM
            eD4gVy3P+Kw3eqjMneD+/caeM+wX5bZD5SffD+I+Er8Qh0pXQzC8HXcj3jFOpF55
            NErXVXKwDlibHppbJU5JzjJAgK91cjxxod0VxOLuqPcLp3bPh5Ee8+dYwtR7ZmV9
            qmedWtaKpu7bwLlKU0pRWbR22ufBoLlg123zedzi9jBFuMXMavPtJhI3/PsxKRK1
            cH6DBwq3/ryNVk+HWDK0ggWIu1hlHWKm1HbSZvBNoL3RfPGBdluCBDThOs9GrB17
            S15/bxFYyTVdy/qMyyhL969HLzVDfxarVCgyGexHUk3lgdollrSYktRsPYsklSdE
            rODQhEwBOX+7fB+LOXUKUevBxrRsXY+RBbRSqMG3+3AbdCduW+IoOIHGdns6+rY4
            N2I4PNw7IK8SJT/ju/87fuNnIK8fMaeFT7ehqCuYLDG5+mIA5zWuVBmamZnNEMHU
            aAEJAhCJJQiD9T238NK7kCIoCCM0p9xaoG05ZgQl2YiBgMIypU0qRtOKLNGs+Mny
            LmuakzMCn4LBXxEf80wpETrp2kAIszX294IHi9akTwJx4+cC3j7QAAf0CdOHl4PZ
            X1rYV/mdgYL2
            =eP4P
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:NRcMkDXuL3iYGI4a5TrIYVYSEOIOgs5P48/gXp0YAaI209QO7YzlfLNw1JOuWKTVpJjmkQS6xbRtMWMx9BWhrw2TkE6V3knJPzjx0gjtLaMiJ6Z5XkX98pA1kj3/xzNEyYbNCmUjoLLnYuXX+Zm10TNzuz8lQMBKnKtb3etvrEzaX5VgOaX1933syP7CGy85hyODGuDOit5Zsq0QkC7bd7a/rCCkuZ5+cYmH69NJ8q0DtysKoQfFU7aGBRFtVuVJSylSZgmaAgcpEniRCDY7acV+Bhl7GdYfR/2DTd7GaIWLD5co1EkrJTamDHh2/RqLVgpRRIHoJdoiJr+7fKuStXlPHinyYIU3QbPZeSsOB+p2Hoh44/jGfDcOMN7bcAZFEYu6OHliFRMC/9YZySJvOE8ArfUxs5bnywLMRf6RB7kDwDHKb93bcplRzGRhPJRXoX8q61sIHNIdPVdGFybj+KflVcNoCqfFvPlukeowUb/XeblkJUIYwYz90FQjOvRqXjd0J+rv9J9XIqkcZFMwaRZwgFhWc6nF0D4m8roJOmhxHmOvlrv65HPnIVg7/nBZbYB/0KU1Jms2ry5PsD3TEt6slsYBy3IVaGU=,iv:68oY99LgDLJragvU7ppHxO3305x+bEXUIr806DcVX/8=,tag:coq9fgf3om3HgjtDEhX5nA==,type:str]
sops:
    lastmodified: "2026-02-24T20:31:10Z"
    mac: ENC[AES256_GCM,data:vXmKwGKM4/7q7YPt7JSZxWrHk3jKf3LaQRWPdu7o9g4QqLhmBrhwVld7BKI4qYHzKtOqKJC2hcmBs7ofBIrWk99GVmBtEJenmxEVluxwJo2NxFxVVYl3XY3BVEvlmgMnirEyXS6buMS4Gt6DG4eq/dwMx/zjCltWcryGvGfp8XM=,iv:dKXatRzpLhtkq+SV/Sd4cj3rdF60fko+CBEAv9ncJB8=,tag:Bbeeimc80k415CB7GjRFHg==,type:str]
    pgp:
        - created_at: "2026-02-24T20:31:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ/+MCNjnYRFZRCTEtNlrxLOfEtwMts+bT7sR6va2z1WE+FH
            VEHaGVj0EeD3e+mNcVZ26IKbiiZz9n3WdXfi9T+oBf1l4gt+tXINjFpn86Gji8+D
            Z5QdL7QiA8XnuKPE3ELGJ+FgWHkzzrHGx7rYQmrqsYIU4T04SKoVudZemwt0lNBU
            sNGjdyYImdQCYxRzGwOQ+QFwqIvvjEDbtVtQneRrT6rfbaQvRd7mwjYpqLCnvZGM
            eD4gVy3P+Kw3eqjMneD+/caeM+wX5bZD5SffD+I+Er8Qh0pXQzC8HXcj3jFOpF55
            NErXVXKwDlibHppbJU5JzjJAgK91cjxxod0VxOLuqPcLp3bPh5Ee8+dYwtR7ZmV9
            qmedWtaKpu7bwLlKU0pRWbR22ufBoLlg123zedzi9jBFuMXMavPtJhI3/PsxKRK1
            cH6DBwq3/ryNVk+HWDK0ggWIu1hlHWKm1HbSZvBNoL3RfPGBdluCBDThOs9GrB17
            S15/bxFYyTVdy/qMyyhL969HLzVDfxarVCgyGexHUk3lgdollrSYktRsPYsklSdE
            rODQhEwBOX+7fB+LOXUKUevBxrRsXY+RBbRSqMG3+3AbdCduW+IoOIHGdns6+rY4
            N2I4PNw7IK8SJT/ju/87fuNnIK8fMaeFT7ehqCuYLDG5+mIA5zWuVBmamZnNEMHU
            aAEJAhCJJQiD9T238NK7kCIoCCM0p9xaoG05ZgQl2YiBgMIypU0qRtOKLNGs+Mny
            LmuakzMCn4LBXxEf80wpETrp2kAIszX294IHi9akTwJx4+cC3j7QAAf0CdOHl4PZ
            X1rYV/mdgYL2
            =eP4P
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:XH+vVG2lDBj2qDV0jApA5BmmwGrCTSEuL/MbPmi9Q0QNx5HYDZJGcBSQ3rErP1X1nopfSuyOVXQT+9ytLkKa0WrisJ6tS7VCO3qwxBAtV5rQYHDohY6TyJLHoORHh5JtgBhLc0+cx50ytlKB2fJDrMAFWqhIuM9h/aNuekq0GKxvgD2ytfI962BkGxE1kz5lkkGxI/gdNjelsA2K2MvY1IfJnI0aKOZZDNeMDw9L42dXmomJbxjJk5PlJlU6F6dgzhf6Jh3sh06dpyMllfaC77AwWSb+vT7LuXHxFBURXOEJt+sCFw7XSAlNU48Q5Bys2JtQ,iv:KgX5pMRzoIkLGkqw1/RBHCvDO6gsWd92b/2ypc8ThGM=,tag:b0GF5gnix+Ve9MusT8AczQ==,type:str]
sops:
    lastmodified: "2026-02-24T20:31:10Z"
    mac: ENC[AES256_GCM,data:vXmKwGKM4/7q7YPt7JSZxWrHk3jKf3LaQRWPdu7o9g4QqLhmBrhwVld7BKI4qYHzKtOqKJC2hcmBs7ofBIrWk99GVmBtEJenmxEVluxwJo2NxFxVVYl3XY3BVEvlmgMnirEyXS6buMS4Gt6DG4eq/dwMx/zjCltWcryGvGfp8XM=,iv:dKXatRzpLhtkq+SV/Sd4cj3rdF60fko+CBEAv9ncJB8=,tag:Bbeeimc80k415CB7GjRFHg==,type:str]
    pgp:
        - created_at: "2026-02-24T20:31:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ/+MCNjnYRFZRCTEtNlrxLOfEtwMts+bT7sR6va2z1WE+FH
            VEHaGVj0EeD3e+mNcVZ26IKbiiZz9n3WdXfi9T+oBf1l4gt+tXINjFpn86Gji8+D
            Z5QdL7QiA8XnuKPE3ELGJ+FgWHkzzrHGx7rYQmrqsYIU4T04SKoVudZemwt0lNBU
            sNGjdyYImdQCYxRzGwOQ+QFwqIvvjEDbtVtQneRrT6rfbaQvRd7mwjYpqLCnvZGM
            eD4gVy3P+Kw3eqjMneD+/caeM+wX5bZD5SffD+I+Er8Qh0pXQzC8HXcj3jFOpF55
            NErXVXKwDlibHppbJU5JzjJAgK91cjxxod0VxOLuqPcLp3bPh5Ee8+dYwtR7ZmV9
            qmedWtaKpu7bwLlKU0pRWbR22ufBoLlg123zedzi9jBFuMXMavPtJhI3/PsxKRK1
            cH6DBwq3/ryNVk+HWDK0ggWIu1hlHWKm1HbSZvBNoL3RfPGBdluCBDThOs9GrB17
            S15/bxFYyTVdy/qMyyhL969HLzVDfxarVCgyGexHUk3lgdollrSYktRsPYsklSdE
            rODQhEwBOX+7fB+LOXUKUevBxrRsXY+RBbRSqMG3+3AbdCduW+IoOIHGdns6+rY4
            N2I4PNw7IK8SJT/ju/87fuNnIK8fMaeFT7ehqCuYLDG5+mIA5zWuVBmamZnNEMHU
            aAEJAhCJJQiD9T238NK7kCIoCCM0p9xaoG05ZgQl2YiBgMIypU0qRtOKLNGs+Mny
            LmuakzMCn4LBXxEf80wpETrp2kAIszX294IHi9akTwJx4+cC3j7QAAf0CdOHl4PZ
            X1rYV/mdgYL2
            =eP4P
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage-s3cmd
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:e+NIbTvjYyqwCjLDheNDoTLwGIFI8bMpTG9/GBIxJJxgEOAqw5Gfooek8CaUtuFQG1eJZNrJ0A0xBU7BmlQeWJWnxIvoabvPk1nP8TT13d5fVBLVy4d5Dzl+xJ3yLduZxG35V89JN4w4oSMrA4uUtiZqK7ZB+uYPgzXKPJeDeVas0DjjXSQeP/OKxWedBYbZXn6JjJ6oI8wzyOqvEAFe3DbEPYOvjTc4nW5ZPwLLvJPJIv1eZfOdr1DPbVtEV9O+GnwnaJ0d0Tbin2jO2gOH3C9eb4V9PVUq8tWTOADL0IhjMLLw3IFjazp3kuxQMOdnmwpHkN81eGxCxw11z8Zk6AkCWhE=,iv:JDj+0crLvno+CLhhns8Yuml7pU2rhBZVkoDmFDXRsTA=,tag:QG2jQfOv2mOJpeqnM25D9g==,type:str]
sops:
    lastmodified: "2026-02-24T20:31:10Z"
    mac: ENC[AES256_GCM,data:vXmKwGKM4/7q7YPt7JSZxWrHk3jKf3LaQRWPdu7o9g4QqLhmBrhwVld7BKI4qYHzKtOqKJC2hcmBs7ofBIrWk99GVmBtEJenmxEVluxwJo2NxFxVVYl3XY3BVEvlmgMnirEyXS6buMS4Gt6DG4eq/dwMx/zjCltWcryGvGfp8XM=,iv:dKXatRzpLhtkq+SV/Sd4cj3rdF60fko+CBEAv9ncJB8=,tag:Bbeeimc80k415CB7GjRFHg==,type:str]
    pgp:
        - created_at: "2026-02-24T20:31:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ/+MCNjnYRFZRCTEtNlrxLOfEtwMts+bT7sR6va2z1WE+FH
            VEHaGVj0EeD3e+mNcVZ26IKbiiZz9n3WdXfi9T+oBf1l4gt+tXINjFpn86Gji8+D
            Z5QdL7QiA8XnuKPE3ELGJ+FgWHkzzrHGx7rYQmrqsYIU4T04SKoVudZemwt0lNBU
            sNGjdyYImdQCYxRzGwOQ+QFwqIvvjEDbtVtQneRrT6rfbaQvRd7mwjYpqLCnvZGM
            eD4gVy3P+Kw3eqjMneD+/caeM+wX5bZD5SffD+I+Er8Qh0pXQzC8HXcj3jFOpF55
            NErXVXKwDlibHppbJU5JzjJAgK91cjxxod0VxOLuqPcLp3bPh5Ee8+dYwtR7ZmV9
            qmedWtaKpu7bwLlKU0pRWbR22ufBoLlg123zedzi9jBFuMXMavPtJhI3/PsxKRK1
            cH6DBwq3/ryNVk+HWDK0ggWIu1hlHWKm1HbSZvBNoL3RfPGBdluCBDThOs9GrB17
            S15/bxFYyTVdy/qMyyhL969HLzVDfxarVCgyGexHUk3lgdollrSYktRsPYsklSdE
            rODQhEwBOX+7fB+LOXUKUevBxrRsXY+RBbRSqMG3+3AbdCduW+IoOIHGdns6+rY4
            N2I4PNw7IK8SJT/ju/87fuNnIK8fMaeFT7ehqCuYLDG5+mIA5zWuVBmamZnNEMHU
            aAEJAhCJJQiD9T238NK7kCIoCCM0p9xaoG05ZgQl2YiBgMIypU0qRtOKLNGs+Mny
            LmuakzMCn4LBXxEf80wpETrp2kAIszX294IHi9akTwJx4+cC3j7QAAf0CdOHl4PZ
            X1rYV/mdgYL2
            =eP4P
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
