apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:c7lrBKjZpta8EhgxmMBSnkcn0sNjhOgA/6SmVaMZCNs4smDSr9rQN9o=,iv:+Cbzux/n1Oc8URHjWNHfnvLNAa4FEZ8tIGjU3mJ5bqY=,tag:r1/lQMgQlryOFP4Fj6M1aQ==,type:str]
sops:
    lastmodified: "2025-05-26T19:30:37Z"
    mac: ENC[AES256_GCM,data:sjSMyKFK8ZiPMtugYjEx/GrIboLLhO3reBN7dnZznRu2NYOufC6GW5S9OJFIkylmqTTGHoXEr5OENfbLHbEiJNmXI3vN9fcgVIfJ/Nl+4OsMmkujthOmArvK+KcmFT6ec7RIFw0uoAwhDc6NdoCTy47lB/RB/+kRAgMwJJtjxaA=,iv:KZDn16bY7SkR2pZRG9/XvCTpHDPpPvBNKFTw/0A2zOw=,tag:xYwqWJC49dCIdQPzsLlKvQ==,type:str]
    pgp:
        - created_at: "2025-05-26T19:30:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//beclfZIn9VFHYrUfQfcs2Oyt1j61fuUOuL+M+RHKDC0y
            wTY8q/MgIfYtRdeMEGPH2UGxi0qcxzsmgJ+94FiBF43kbwlBR4sNwcDt02sotJ6a
            zMKYLBRl0bfLY0NqNQcT540Nmk0bXdtSBWumhjQTVi6MfHe/dadClw9E7iDn+rM7
            rasEMpKkxxs50MShmmDiCzCjWwjKv3/PNh8uT0R+pwRUBej49BlUBSBZNQjNjmRU
            UV2uaWwB/ZuuB+6hGI2EAq1ayIRWQOvhv8CO39yoNG++lRk2IDv/xVOKcwBNB796
            Cimt6AWWxzznf2SMR0UfM/sNLqUkaN3FBYiLbWb2A13R6Emd/IE99x+cFd363kij
            rHX/PQqvmfG3IEeDdGVN7oKvJ4YfzSE4JyJfPbmZDsoMdDkUR66yMwkoXlCHbHoQ
            FDqDoW40Bw87JGQYfYCXtnAy4VSB9/sXprHzjqUaLbFIP746GkijQmRkAWn8TyWK
            vYxCglGoRw27lAHW3QKuwKB8fNX7u2Kb6KM3qpfctUcBEEpfBKRy+G/Z8aclfTqT
            sX8A9caYNKZCMvdYr1nnVUZpdzlvcZft9QUQ8AHmcuUThBtVGN50fGxGGikTczCf
            +DtoTfqr4O2i7g1x6iueBnqYXj7O874AdfidbAp/tRm9ESzigGOgGGIuvK94XrrU
            ZgEJAhBaIwcCyB4GlruDpGKKXUbRv2StkJGB2EmZemiEMV2l33mCF5yPk1JLAQs/
            CJTzCQYtvfDue4vTAyrpQ3hTbt2MA+CZNExtlqqsuCUjMrDF9OBfQsfhVo4hikM5
            fNv1g0451w==
            =TtQ/
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:CJ93t9sLwBM1nb4e9AnW/8vmCUja7888DgiyWHDATHE=,iv:jsZLPEouTTxHXvr80Htj2/qT7lclw/PAffeH2GATaAg=,tag:IrcIghTvOf59RrlMsej7nw==,type:str]
sops:
    lastmodified: "2025-05-26T19:30:37Z"
    mac: ENC[AES256_GCM,data:sjSMyKFK8ZiPMtugYjEx/GrIboLLhO3reBN7dnZznRu2NYOufC6GW5S9OJFIkylmqTTGHoXEr5OENfbLHbEiJNmXI3vN9fcgVIfJ/Nl+4OsMmkujthOmArvK+KcmFT6ec7RIFw0uoAwhDc6NdoCTy47lB/RB/+kRAgMwJJtjxaA=,iv:KZDn16bY7SkR2pZRG9/XvCTpHDPpPvBNKFTw/0A2zOw=,tag:xYwqWJC49dCIdQPzsLlKvQ==,type:str]
    pgp:
        - created_at: "2025-05-26T19:30:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//beclfZIn9VFHYrUfQfcs2Oyt1j61fuUOuL+M+RHKDC0y
            wTY8q/MgIfYtRdeMEGPH2UGxi0qcxzsmgJ+94FiBF43kbwlBR4sNwcDt02sotJ6a
            zMKYLBRl0bfLY0NqNQcT540Nmk0bXdtSBWumhjQTVi6MfHe/dadClw9E7iDn+rM7
            rasEMpKkxxs50MShmmDiCzCjWwjKv3/PNh8uT0R+pwRUBej49BlUBSBZNQjNjmRU
            UV2uaWwB/ZuuB+6hGI2EAq1ayIRWQOvhv8CO39yoNG++lRk2IDv/xVOKcwBNB796
            Cimt6AWWxzznf2SMR0UfM/sNLqUkaN3FBYiLbWb2A13R6Emd/IE99x+cFd363kij
            rHX/PQqvmfG3IEeDdGVN7oKvJ4YfzSE4JyJfPbmZDsoMdDkUR66yMwkoXlCHbHoQ
            FDqDoW40Bw87JGQYfYCXtnAy4VSB9/sXprHzjqUaLbFIP746GkijQmRkAWn8TyWK
            vYxCglGoRw27lAHW3QKuwKB8fNX7u2Kb6KM3qpfctUcBEEpfBKRy+G/Z8aclfTqT
            sX8A9caYNKZCMvdYr1nnVUZpdzlvcZft9QUQ8AHmcuUThBtVGN50fGxGGikTczCf
            +DtoTfqr4O2i7g1x6iueBnqYXj7O874AdfidbAp/tRm9ESzigGOgGGIuvK94XrrU
            ZgEJAhBaIwcCyB4GlruDpGKKXUbRv2StkJGB2EmZemiEMV2l33mCF5yPk1JLAQs/
            CJTzCQYtvfDue4vTAyrpQ3hTbt2MA+CZNExtlqqsuCUjMrDF9OBfQsfhVo4hikM5
            fNv1g0451w==
            =TtQ/
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:6KK7/fo2EsPHnC6hvfAD7mV+BnHzN2CtRDWqZ0Z+z14roMCHTgoKVe0NZagVUzblVSdeE7X3DZMNn2tL99wkiSCmoyVXc+tF1yVIl4hfrprn47k80MeDJJgQUk8Qxtc+3WPytd22Ng3o2Fswf2kLnIW5Qc4SHkAjW9JjMO082e2BwX8zgsLCgQc2VDIZOAO1P9PSHMJJNB2Yrq2/qr6oZcz8oHSGCnXccrpvKcluudNNtSaT8NscdAMTF2LnGZaa0QwNSI1CnpxbV/r8fhpkXTImdqjaCbcuCUPDohzq0vYgC81zIz63LVXGnoZDJrA3Usecw4kvy1TPHHiIM4tzPQMoWxjIdmNw+694M+RzJb08lENatyBtOS05SE43DU9rPP/NikHlBRNtI8umigasYk5fetqyAUiarwBqTT7deq0MRVZZPYZ4L+7FwWssGTtegnSVgKka++P09B6k0LehiBHe0wpH5z0XQK9hrioc+geYoFBgVCP8SYIb8RhhC5yh+Jd9Ywwkuq0+TsLR3kzZKoeQtpBZeiDTLuE2NXylQFxOcOM4hbFDamulwvRQ5FMuKgZsE1xLErfB3ivfOpK4uXtdU4rk5W4hg8w=,iv:Xc0xJIY3bRSRkZjNcOAadZ8xradkc2idzILBGebXG/M=,tag:WxqGsIeP90kicCrdxzgARA==,type:str]
sops:
    lastmodified: "2025-05-26T19:30:37Z"
    mac: ENC[AES256_GCM,data:sjSMyKFK8ZiPMtugYjEx/GrIboLLhO3reBN7dnZznRu2NYOufC6GW5S9OJFIkylmqTTGHoXEr5OENfbLHbEiJNmXI3vN9fcgVIfJ/Nl+4OsMmkujthOmArvK+KcmFT6ec7RIFw0uoAwhDc6NdoCTy47lB/RB/+kRAgMwJJtjxaA=,iv:KZDn16bY7SkR2pZRG9/XvCTpHDPpPvBNKFTw/0A2zOw=,tag:xYwqWJC49dCIdQPzsLlKvQ==,type:str]
    pgp:
        - created_at: "2025-05-26T19:30:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//beclfZIn9VFHYrUfQfcs2Oyt1j61fuUOuL+M+RHKDC0y
            wTY8q/MgIfYtRdeMEGPH2UGxi0qcxzsmgJ+94FiBF43kbwlBR4sNwcDt02sotJ6a
            zMKYLBRl0bfLY0NqNQcT540Nmk0bXdtSBWumhjQTVi6MfHe/dadClw9E7iDn+rM7
            rasEMpKkxxs50MShmmDiCzCjWwjKv3/PNh8uT0R+pwRUBej49BlUBSBZNQjNjmRU
            UV2uaWwB/ZuuB+6hGI2EAq1ayIRWQOvhv8CO39yoNG++lRk2IDv/xVOKcwBNB796
            Cimt6AWWxzznf2SMR0UfM/sNLqUkaN3FBYiLbWb2A13R6Emd/IE99x+cFd363kij
            rHX/PQqvmfG3IEeDdGVN7oKvJ4YfzSE4JyJfPbmZDsoMdDkUR66yMwkoXlCHbHoQ
            FDqDoW40Bw87JGQYfYCXtnAy4VSB9/sXprHzjqUaLbFIP746GkijQmRkAWn8TyWK
            vYxCglGoRw27lAHW3QKuwKB8fNX7u2Kb6KM3qpfctUcBEEpfBKRy+G/Z8aclfTqT
            sX8A9caYNKZCMvdYr1nnVUZpdzlvcZft9QUQ8AHmcuUThBtVGN50fGxGGikTczCf
            +DtoTfqr4O2i7g1x6iueBnqYXj7O874AdfidbAp/tRm9ESzigGOgGGIuvK94XrrU
            ZgEJAhBaIwcCyB4GlruDpGKKXUbRv2StkJGB2EmZemiEMV2l33mCF5yPk1JLAQs/
            CJTzCQYtvfDue4vTAyrpQ3hTbt2MA+CZNExtlqqsuCUjMrDF9OBfQsfhVo4hikM5
            fNv1g0451w==
            =TtQ/
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
