apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:VOlpcK+5tEuz0nM3Lu5iI901I3T3X9j1C6eQapVXdHIgE54ohM2SxKY=,iv:W/6/1TVDOAaA1bQTiYELgf1vNKAKOeUMmuB+AnDASZ0=,tag:ATrS3LI55CpNns0eJDyVmQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:40:41Z"
    mac: ENC[AES256_GCM,data:1h3njCSi5E4dEg8HTb/IpHGeVIMyTjfIjEVPTbUB+6fceiry6xyRrf3VhZbsEfUDMQycbTVTSmWsOY8tLulfP8GHBg8nDpyxKwnj5s8/WB6CMy4kTZL/wrWtgZ1wOcsktZQWXufPXmlyywQ6quqiWG0/PI0ZmYwZ75RYsHqyj1A=,iv:Bpnozfn5uj7qV87zLrbKR6jiINYeN/mdgiETEyAumDY=,tag:n7m7QJEy2wl8jIrcY4wH1Q==,type:str]
    pgp:
        - created_at: "2026-05-22T08:40:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqWAFWHdqFhMayD8blGu8iQJJjabQrOHSfpowRb82lm8b
            Ff3eySttQFCrwXWf4y9zGmv+UjesIdOQoP4MamN96Riz4w2leTZxy652nalARHtn
            PPD8J2ixwpbB2TCa5Shi1kiUCd5ALUd+Asd1sczY8dZ8XhpG1zubIlPC+JfbKui5
            eKjdH2hZa5tDNksHPhnmXy7SMeKQMI8yugxH2ixNZ1souQWHgIGVAw4L7bATZSti
            eliZRu1Wz/kYlIvZKab90Y0yxRTMl5dWWqVMCfX/86E4SLGjyZHvdAlzQi61G2W2
            uP/UvP1JhtTc96JDFbGGBKYelbqj2bmm5ZjLhd49qntWNWkj4FdfKUvk3bkSRP1o
            dTcNqJYZe4MoNJjeHH8iKSFFBnZlVyZrXmXhwoddJgZfECULfAUkD2ksIF4EaJUm
            k0Nk7O25rd77WoV0pLgmK0ylkodT2tSmRskQigonkisjDjyiJvadEwV8iyrURRCB
            QXwP6740bZma762rI30kA8VznPQF57Nr8av9ZGRPaj9L3jKv4TCbTcF2lmcJUPum
            5XSkCnRhA5F74c8uo7m8UdP74kwuOlH0/LlyIwcx7kR6V7Dwd5tlOID7n6dSANV0
            bI33G2/V1fB2E/m5Gy4KcWj0TB9W1tq7iu+auwXYYEsDS0r6sWuiu+snATiUdl7U
            aAEJAhA9+CEjiTJjBg2v5BCBeIM/I42IlO1GfqeDKO+ItcWoe3IlMRUb5snwkrBJ
            TOvCRp17g8QTFI2JRRMjzuasXK2pIVnG/Pa8+xV6/AkDane5vwqaP/dm4RE5QrTO
            uHb9AheWY72G
            =cheu
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:/DGQJZbgow960CgmjmbtnU1asQXDvsM2tV04TG+DzDg=,iv:lN2/ByjBtCOuD0N6xmcXUT+zTyFnorr5E+Gv8D1igbQ=,tag:hJyNM39ZA+CE7EcddlRTgA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:40:41Z"
    mac: ENC[AES256_GCM,data:1h3njCSi5E4dEg8HTb/IpHGeVIMyTjfIjEVPTbUB+6fceiry6xyRrf3VhZbsEfUDMQycbTVTSmWsOY8tLulfP8GHBg8nDpyxKwnj5s8/WB6CMy4kTZL/wrWtgZ1wOcsktZQWXufPXmlyywQ6quqiWG0/PI0ZmYwZ75RYsHqyj1A=,iv:Bpnozfn5uj7qV87zLrbKR6jiINYeN/mdgiETEyAumDY=,tag:n7m7QJEy2wl8jIrcY4wH1Q==,type:str]
    pgp:
        - created_at: "2026-05-22T08:40:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqWAFWHdqFhMayD8blGu8iQJJjabQrOHSfpowRb82lm8b
            Ff3eySttQFCrwXWf4y9zGmv+UjesIdOQoP4MamN96Riz4w2leTZxy652nalARHtn
            PPD8J2ixwpbB2TCa5Shi1kiUCd5ALUd+Asd1sczY8dZ8XhpG1zubIlPC+JfbKui5
            eKjdH2hZa5tDNksHPhnmXy7SMeKQMI8yugxH2ixNZ1souQWHgIGVAw4L7bATZSti
            eliZRu1Wz/kYlIvZKab90Y0yxRTMl5dWWqVMCfX/86E4SLGjyZHvdAlzQi61G2W2
            uP/UvP1JhtTc96JDFbGGBKYelbqj2bmm5ZjLhd49qntWNWkj4FdfKUvk3bkSRP1o
            dTcNqJYZe4MoNJjeHH8iKSFFBnZlVyZrXmXhwoddJgZfECULfAUkD2ksIF4EaJUm
            k0Nk7O25rd77WoV0pLgmK0ylkodT2tSmRskQigonkisjDjyiJvadEwV8iyrURRCB
            QXwP6740bZma762rI30kA8VznPQF57Nr8av9ZGRPaj9L3jKv4TCbTcF2lmcJUPum
            5XSkCnRhA5F74c8uo7m8UdP74kwuOlH0/LlyIwcx7kR6V7Dwd5tlOID7n6dSANV0
            bI33G2/V1fB2E/m5Gy4KcWj0TB9W1tq7iu+auwXYYEsDS0r6sWuiu+snATiUdl7U
            aAEJAhA9+CEjiTJjBg2v5BCBeIM/I42IlO1GfqeDKO+ItcWoe3IlMRUb5snwkrBJ
            TOvCRp17g8QTFI2JRRMjzuasXK2pIVnG/Pa8+xV6/AkDane5vwqaP/dm4RE5QrTO
            uHb9AheWY72G
            =cheu
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:/LuFA7dmtauWcHQu6NYI/dD3CsnvmTrIVmuNIblc9w2dHMj21QpRG6A7vx8KYWrNoAAdWllZezB/J+ue2G7YpPNj372woO4WE+i2fdP8HB6xx7aQQ8oqfumQR55MyhG4A+JqQktFilXAhl0hsj4d8+nvN4cpXOWvG8QU//SeIKSz+eGnTzpNc2V9UZvVt3Zf9mkdF9JKWLSwHDM78s+jXKJiQlNmZCTeT7cAOiCWp9JDEtoPZSjooLdeGqlTFmjWbQF76mdEn2DowqjB8poYjoawLen30ZNkzSUf9Oj5ZiWfqWAS1YUZk8adf2X4hJc/SLqRhZe8bv3+9E1WZBza+l/ZbaLe/q5NrSpefp0w3exGnJww9kuD/qZTgQfjN1/i8aILXLeeW0m2WSLUtdk/pONJOvQi/MmgG0L1hToCIsCztiDwNzhZQTL1dwKOtjd1DdmM+GzrwRGpR/ZATy8uwGsTa0r6WIT/clldL11iQEFTdQ/ivIWFj2emFTvOC9/XQDrqevATYh8IKMDqcbP6FVU4MaffbHMYqBl53vY61MNzs0E30h/ZVG1zOD9xsdlYYYSVbVc2U+gp9i3qYa57gAvb0okgjeJRukU=,iv:l+H1hrtZB5O30yOk4BCO6YitJ3FnJD7SlfcilfR3Q8Y=,tag:KlbSactZ4F9ZHEgImKhKCw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:40:41Z"
    mac: ENC[AES256_GCM,data:1h3njCSi5E4dEg8HTb/IpHGeVIMyTjfIjEVPTbUB+6fceiry6xyRrf3VhZbsEfUDMQycbTVTSmWsOY8tLulfP8GHBg8nDpyxKwnj5s8/WB6CMy4kTZL/wrWtgZ1wOcsktZQWXufPXmlyywQ6quqiWG0/PI0ZmYwZ75RYsHqyj1A=,iv:Bpnozfn5uj7qV87zLrbKR6jiINYeN/mdgiETEyAumDY=,tag:n7m7QJEy2wl8jIrcY4wH1Q==,type:str]
    pgp:
        - created_at: "2026-05-22T08:40:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqWAFWHdqFhMayD8blGu8iQJJjabQrOHSfpowRb82lm8b
            Ff3eySttQFCrwXWf4y9zGmv+UjesIdOQoP4MamN96Riz4w2leTZxy652nalARHtn
            PPD8J2ixwpbB2TCa5Shi1kiUCd5ALUd+Asd1sczY8dZ8XhpG1zubIlPC+JfbKui5
            eKjdH2hZa5tDNksHPhnmXy7SMeKQMI8yugxH2ixNZ1souQWHgIGVAw4L7bATZSti
            eliZRu1Wz/kYlIvZKab90Y0yxRTMl5dWWqVMCfX/86E4SLGjyZHvdAlzQi61G2W2
            uP/UvP1JhtTc96JDFbGGBKYelbqj2bmm5ZjLhd49qntWNWkj4FdfKUvk3bkSRP1o
            dTcNqJYZe4MoNJjeHH8iKSFFBnZlVyZrXmXhwoddJgZfECULfAUkD2ksIF4EaJUm
            k0Nk7O25rd77WoV0pLgmK0ylkodT2tSmRskQigonkisjDjyiJvadEwV8iyrURRCB
            QXwP6740bZma762rI30kA8VznPQF57Nr8av9ZGRPaj9L3jKv4TCbTcF2lmcJUPum
            5XSkCnRhA5F74c8uo7m8UdP74kwuOlH0/LlyIwcx7kR6V7Dwd5tlOID7n6dSANV0
            bI33G2/V1fB2E/m5Gy4KcWj0TB9W1tq7iu+auwXYYEsDS0r6sWuiu+snATiUdl7U
            aAEJAhA9+CEjiTJjBg2v5BCBeIM/I42IlO1GfqeDKO+ItcWoe3IlMRUb5snwkrBJ
            TOvCRp17g8QTFI2JRRMjzuasXK2pIVnG/Pa8+xV6/AkDane5vwqaP/dm4RE5QrTO
            uHb9AheWY72G
            =cheu
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:izZmTbQ4i6dzoOKsANwLvHK2w3+z42Uy25XaS6ZZ+FRmbUrnc+M5TIJQV9QKkCIjheollLOAJ7L/89pF0Tld3O2AlI3AuVVT8x2Ze4kyW9q3B8h2wR1a3qHjXgMGnagm5mzeun79TtYtHdzPbRawYvQIldHnB0/GwnQAc3GNj3O8dOKsANiTWcDFdh5E3pAEa7WdULMKLyCwEg2zid7odtUwUdzc7oEEeEl/TWy/EDjQQLZw8/RvPAA6hmNMUpwU+aDYY1yE6S+YSqjAU+Ye+PoPrm66GJZzZie9fdt/zKSObQ9IaZaxE3lB+rc1oWGT5hHB,iv:4ZKJsdnBXQmMYrf/arMX7L7knr4XvVXLQ8EjCHwZfaY=,tag:LhJQtl01gwj241X+u87utw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:40:41Z"
    mac: ENC[AES256_GCM,data:1h3njCSi5E4dEg8HTb/IpHGeVIMyTjfIjEVPTbUB+6fceiry6xyRrf3VhZbsEfUDMQycbTVTSmWsOY8tLulfP8GHBg8nDpyxKwnj5s8/WB6CMy4kTZL/wrWtgZ1wOcsktZQWXufPXmlyywQ6quqiWG0/PI0ZmYwZ75RYsHqyj1A=,iv:Bpnozfn5uj7qV87zLrbKR6jiINYeN/mdgiETEyAumDY=,tag:n7m7QJEy2wl8jIrcY4wH1Q==,type:str]
    pgp:
        - created_at: "2026-05-22T08:40:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqWAFWHdqFhMayD8blGu8iQJJjabQrOHSfpowRb82lm8b
            Ff3eySttQFCrwXWf4y9zGmv+UjesIdOQoP4MamN96Riz4w2leTZxy652nalARHtn
            PPD8J2ixwpbB2TCa5Shi1kiUCd5ALUd+Asd1sczY8dZ8XhpG1zubIlPC+JfbKui5
            eKjdH2hZa5tDNksHPhnmXy7SMeKQMI8yugxH2ixNZ1souQWHgIGVAw4L7bATZSti
            eliZRu1Wz/kYlIvZKab90Y0yxRTMl5dWWqVMCfX/86E4SLGjyZHvdAlzQi61G2W2
            uP/UvP1JhtTc96JDFbGGBKYelbqj2bmm5ZjLhd49qntWNWkj4FdfKUvk3bkSRP1o
            dTcNqJYZe4MoNJjeHH8iKSFFBnZlVyZrXmXhwoddJgZfECULfAUkD2ksIF4EaJUm
            k0Nk7O25rd77WoV0pLgmK0ylkodT2tSmRskQigonkisjDjyiJvadEwV8iyrURRCB
            QXwP6740bZma762rI30kA8VznPQF57Nr8av9ZGRPaj9L3jKv4TCbTcF2lmcJUPum
            5XSkCnRhA5F74c8uo7m8UdP74kwuOlH0/LlyIwcx7kR6V7Dwd5tlOID7n6dSANV0
            bI33G2/V1fB2E/m5Gy4KcWj0TB9W1tq7iu+auwXYYEsDS0r6sWuiu+snATiUdl7U
            aAEJAhA9+CEjiTJjBg2v5BCBeIM/I42IlO1GfqeDKO+ItcWoe3IlMRUb5snwkrBJ
            TOvCRp17g8QTFI2JRRMjzuasXK2pIVnG/Pa8+xV6/AkDane5vwqaP/dm4RE5QrTO
            uHb9AheWY72G
            =cheu
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:DuxC7ZNGxBwBUYLsCW9aHZhtFEoNCruzkZptRcxxaaNeNnIU46SWZg8Jj377LkULSyFl4HIV1VOw+Zqr8k9E/YXi2CFiMc9GyrNEkx8I6QzWbHA5S0T8k7dXYZwzYieFq/LivPRdVb6nUZB673VJt0EWI9KIuXmSbcMdY+XSqcUDX4gL883P6ftVp7iU5puBQRhNWUjI2+F1u/ddeA2Tt7jtwLj3bBg4YsM2RTrMuUcwyS5vqit4N3gnj12Z7OKATTSNmDzkuyfelKMoWBZ5rt0EGA2cD26e9mUT0bteCMQ6UIXsSl4+BO6qOK8p/nKl/fzd+gj2M3MgtSe5SKXG8DNTty4=,iv:NeLd0GS5JqDy8q8/Br3M2mUGuypwGvl9+G3CutKL8Hw=,tag:U3wWexMFXdrg6Mp1Mi+Ycw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:40:41Z"
    mac: ENC[AES256_GCM,data:1h3njCSi5E4dEg8HTb/IpHGeVIMyTjfIjEVPTbUB+6fceiry6xyRrf3VhZbsEfUDMQycbTVTSmWsOY8tLulfP8GHBg8nDpyxKwnj5s8/WB6CMy4kTZL/wrWtgZ1wOcsktZQWXufPXmlyywQ6quqiWG0/PI0ZmYwZ75RYsHqyj1A=,iv:Bpnozfn5uj7qV87zLrbKR6jiINYeN/mdgiETEyAumDY=,tag:n7m7QJEy2wl8jIrcY4wH1Q==,type:str]
    pgp:
        - created_at: "2026-05-22T08:40:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqWAFWHdqFhMayD8blGu8iQJJjabQrOHSfpowRb82lm8b
            Ff3eySttQFCrwXWf4y9zGmv+UjesIdOQoP4MamN96Riz4w2leTZxy652nalARHtn
            PPD8J2ixwpbB2TCa5Shi1kiUCd5ALUd+Asd1sczY8dZ8XhpG1zubIlPC+JfbKui5
            eKjdH2hZa5tDNksHPhnmXy7SMeKQMI8yugxH2ixNZ1souQWHgIGVAw4L7bATZSti
            eliZRu1Wz/kYlIvZKab90Y0yxRTMl5dWWqVMCfX/86E4SLGjyZHvdAlzQi61G2W2
            uP/UvP1JhtTc96JDFbGGBKYelbqj2bmm5ZjLhd49qntWNWkj4FdfKUvk3bkSRP1o
            dTcNqJYZe4MoNJjeHH8iKSFFBnZlVyZrXmXhwoddJgZfECULfAUkD2ksIF4EaJUm
            k0Nk7O25rd77WoV0pLgmK0ylkodT2tSmRskQigonkisjDjyiJvadEwV8iyrURRCB
            QXwP6740bZma762rI30kA8VznPQF57Nr8av9ZGRPaj9L3jKv4TCbTcF2lmcJUPum
            5XSkCnRhA5F74c8uo7m8UdP74kwuOlH0/LlyIwcx7kR6V7Dwd5tlOID7n6dSANV0
            bI33G2/V1fB2E/m5Gy4KcWj0TB9W1tq7iu+auwXYYEsDS0r6sWuiu+snATiUdl7U
            aAEJAhA9+CEjiTJjBg2v5BCBeIM/I42IlO1GfqeDKO+ItcWoe3IlMRUb5snwkrBJ
            TOvCRp17g8QTFI2JRRMjzuasXK2pIVnG/Pa8+xV6/AkDane5vwqaP/dm4RE5QrTO
            uHb9AheWY72G
            =cheu
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage-s3cmd
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:R8wzAibfRBH0rpUJZuUeiOPs12kykfG1ZAZB76jSLTwFSRpxeavPCYQhFleZ5gd5K59EGzxeMAD2JwGXFpBBaEdmC2pctSLXVmMzro7KAnazg+bCY1ehRUsqU25pTjJNuKtIas2AKV7dslLg32ZQiCEHfV++DS6FNm3WqA98z5g5o9es3JNSnbEZuJ1W9m0Yn6Gd6QJyd4PRxKtTemL0YDZYovdFZzDCBZKztOXed6l7I7cbfEyupjIKuZNbmkqUr90re75m12V0OMxB7xJUxL+vjhSNVQHWzciAPdGS7G3rxVPiV+z+KLB24+oUBpuo9J3RhdCVGDDRIDalhDYG56eZABs=,iv:b0DW+UDu02vsEZU2fSU6d/4DFsdBzneo1wK6+06Pojs=,tag:44GkEBpz599xV2mgAhyelA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:40:41Z"
    mac: ENC[AES256_GCM,data:1h3njCSi5E4dEg8HTb/IpHGeVIMyTjfIjEVPTbUB+6fceiry6xyRrf3VhZbsEfUDMQycbTVTSmWsOY8tLulfP8GHBg8nDpyxKwnj5s8/WB6CMy4kTZL/wrWtgZ1wOcsktZQWXufPXmlyywQ6quqiWG0/PI0ZmYwZ75RYsHqyj1A=,iv:Bpnozfn5uj7qV87zLrbKR6jiINYeN/mdgiETEyAumDY=,tag:n7m7QJEy2wl8jIrcY4wH1Q==,type:str]
    pgp:
        - created_at: "2026-05-22T08:40:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/ARAAqWAFWHdqFhMayD8blGu8iQJJjabQrOHSfpowRb82lm8b
            Ff3eySttQFCrwXWf4y9zGmv+UjesIdOQoP4MamN96Riz4w2leTZxy652nalARHtn
            PPD8J2ixwpbB2TCa5Shi1kiUCd5ALUd+Asd1sczY8dZ8XhpG1zubIlPC+JfbKui5
            eKjdH2hZa5tDNksHPhnmXy7SMeKQMI8yugxH2ixNZ1souQWHgIGVAw4L7bATZSti
            eliZRu1Wz/kYlIvZKab90Y0yxRTMl5dWWqVMCfX/86E4SLGjyZHvdAlzQi61G2W2
            uP/UvP1JhtTc96JDFbGGBKYelbqj2bmm5ZjLhd49qntWNWkj4FdfKUvk3bkSRP1o
            dTcNqJYZe4MoNJjeHH8iKSFFBnZlVyZrXmXhwoddJgZfECULfAUkD2ksIF4EaJUm
            k0Nk7O25rd77WoV0pLgmK0ylkodT2tSmRskQigonkisjDjyiJvadEwV8iyrURRCB
            QXwP6740bZma762rI30kA8VznPQF57Nr8av9ZGRPaj9L3jKv4TCbTcF2lmcJUPum
            5XSkCnRhA5F74c8uo7m8UdP74kwuOlH0/LlyIwcx7kR6V7Dwd5tlOID7n6dSANV0
            bI33G2/V1fB2E/m5Gy4KcWj0TB9W1tq7iu+auwXYYEsDS0r6sWuiu+snATiUdl7U
            aAEJAhA9+CEjiTJjBg2v5BCBeIM/I42IlO1GfqeDKO+ItcWoe3IlMRUb5snwkrBJ
            TOvCRp17g8QTFI2JRRMjzuasXK2pIVnG/Pa8+xV6/AkDane5vwqaP/dm4RE5QrTO
            uHb9AheWY72G
            =cheu
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.1
