---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: k8up
      version: 4.8.5
      sourceRef:
        kind: HelmRepository
        name: k8up-io
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: ghcr.io
      repository: k8up-io/k8up
      tag: v2.12.0
    k8up:
      timezone: Europe/Zurich
      skipWithoutAnnotation: true
    metrics:
      prometheusRule:
        enabled: true
        namespace: monitoring
      serviceMonitor:
        enabled: true
        namespace: monitoring
  valuesFrom:
    - kind: Secret
      name: k8up-helm-values
      optional: false
  install:
    crds: Skip
  upgrade:
    crds: Skip
