apiVersion: v1
kind: Secret
metadata:
    name: k8up-helm-values
    namespace: k8up
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Yv21CfQnLFomZGkTNEpKGKSBOEK/F9g2UuMUkqlKYZVnYXsmlC+PNVMY89b2dKxd1mlY++A64bKUW0YMlz7RWn+Um2TwWXz1xUzcVy4wRiILTS8bZSq1RCZjANpcaBFsbXtLoePGZw+8g2UvNT6jgVGT4sxBeuFaYcbXi2EiVDPe0x6okU9jR0EQ4bLdOnNyXSqvOJvJz5rcbMKkOqsWkuS8Iwd82ThU+oD45XMOsYrS3lthr72G0BiwIxL6FJah2TS0bLEBR4fgWcRwk5G5NymuulVbmoVMh4VeG0JzFRtKG2pE/krOogY4oKwSmBVTTttGscDa4pyvT1FSJxALSqNzPsqVzSs+WgtiphA7P1xQxU63w1YuEzBga2BYKYbLJj/PV9a3Dv+KU06iokS2nT0vSFd5guH2f/uUbEu3SWw3Cr+X55kySxzKVamts/BFlURvUasA7XveCbv8FFfCy0RLz7Tm3Q3p7Uugr+SpDHPPz+kLUPP4dIlMQ/Ye6Ne8K9n+HK2DHXvOptYnT2BjH+XCiuWbgnJb+ZokfylweTNPXPRWQ89rWtN5eN11AxRbNnLg7YFUwLG8trUkRmrVOvh+b2VqnpQiDJXXfctwoSVlVRV4Dxfkg5Q=,iv:irT0kY7y9Qg7hWhPEfWd4RGCmr+AJZnx8WA0UHZTpEw=,tag:uiq5EOGLglL5GMoxYE938w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T13:22:53Z"
    mac: ENC[AES256_GCM,data:Gf1il7Lo8Y+4jph0S+w0w06/BcQnqF2qnZ9r9EC1DonSGYelo/Y/tpYT/csW7fspfLlSKkWETmGiBz/Stwnw91hIfTOzQ9z/27wuKEd0jMlbNwZT8FH4IrfZOuKg2h5Is0bc8iDn8p+lBxZPjl7dgkDZ8PAWVLbGaFMg8yQ3Vx8=,iv:VTGBFUEAvfv+dRhwliZz5qswoDys6XTij0qtuutk4pw=,tag:AV3zKdC5k6iKQciUwhSjaA==,type:str]
    pgp:
        - created_at: "2026-09-29T13:22:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8LTdrN3Uc5/AQ//btgVucDkRuT9kaJQSPHufQGixBPpj3w55KRIkgIidLPc
            f0hALJL1eoLelKnpmd3ko3AXh7BlxdC9y6CtiskIqp1WXJwRSBy7tlpX5IV/+E2y
            5PKkdH6fMsqIAv4ig7k416HlFZoHsF3cHE6jAZ200KNb8sjzFZY6e4cWj023JN83
            SEx8elEbfiQcRcYpSKDj9YlS+4jnPbLaN8ApBNWBMiLaOUfX83l2M1s80YqQI1sY
            fbBMfNUmI/W2L1D7o1uzQpL5L8yq6+d62PjfwzWJVrz1LQCGqQHEm5s/v12/Q80y
            jhz09prbOuLwes+BhkKj1UBARqcfvXRm63JQjF2wZxUY+Y4H7HsEKZ3cndN1CTsY
            S+RvLqlq6Aq0+UurSvctz8pV7jdqkvfp5oJp3+d2wbxcV+SFt/kpmUQ6FetDlkLl
            X3WJJ+Mvmi0FTL2KEU5hMpIeRcU7PJXy7vX7dPef1rzukqII9UThoojqBVitQbhg
            KzLZdmk/zvvvKmKvYaPIMXeltTVefxEkZkgj5VbjlxV5u70icsjsgKGDnHfjll9M
            YO4T0PzEzu1hzsq5rQW3nzEbGIs3xComOrGf9pWGtiJsxsaWXzI8/TdiJIayNwzj
            6IAa9Cuk6XVskgbrzl5jbdIjjFmR7Idd+8aTeaj2iasTwv2CBaRcJMbidmKAAjTU
            aAEJAhDHlaPe6l9n0H3RZfVymxffgpOow7texacPKOSuxVzhNveUmbmXoxWeV3aG
            10Rs9Nm8YfIT7o0IicKOIzJC/MDIabGKwxUAjF4AOqWfFVA13qGzXbJlYhB26Bga
            rTBZ1RLaG76y
            =ZqIj
            -----END PGP MESSAGE-----
          fp: 4988A3C9ED6515B2E192F0ABE42278AB326CB047
    version: 3.13.3
