---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-crds
  namespace: envoy-gateway-system
spec:
  interval: 5m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: envoy-gateway-crds
    namespace: flux-system
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    crds:
      gatewayAPI:
        enabled: true
        channel: standard
      envoyGateway:
        enabled: true
