---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: usenet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:5.27.5.10198-ls285
          env:
            - name: PGID
              value: "2000"
            - name: PUID
              value: "2000"
            - name: TZ
              value: Europe/Zurich
            - name: DOCKER_MODS
              value: ghcr.io/themepark-dev/theme.park:radarr
            - name: TP_THEME
              value: catppuccin-mocha
            - name: TP_COMMUNITY_THEME
              value: "true"
          ports:
            - containerPort: 7878
          volumeMounts:
            - mountPath: /config
              name: data
            - mountPath: /config/Backups
              name: backup
            - mountPath: /movies
              name: movies
            - mountPath: /downloads
              name: downloads
          startupProbe:
            tcpSocket:
              port: 7878
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 7878
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: radarr-data
        - name: backup
          persistentVolumeClaim:
            claimName: radarr-backup
        - name: movies
          hostPath:
            path: /mnt/tank/media/movies
            type: Directory
        - name: downloads
          hostPath:
            path: /mnt/disk04/downloads/complete
            type: Directory
